### ISSUE TITLE
False positive on bash 5.2.5-12 for CVE-2022-3715

### ISSUE THREAD

**Issue by zakandrewking** [anchore/grype#1061]
**What happened**:

False positive on bash 5.2.5-12 on debian:bullseye for CVE-2022-3715

**What you expected to happen**:

No false positive

**How to reproduce it (as minimally and precisely as possible)**:

Dockerfile:

```
FROM debian:bullseye
RUN bash -c 'echo "deb http://ftp.us.debian.org/debian unstable main contrib non-free" >> /etc/apt/sources.list.d/unstable.list'
RUN apt-get update \
    && export DEBIAN_FRONTEND=noninteractive \
    && apt-get -y install --on-install-recommends \
    bash/unstable
```

grype reports:
```
bash              5.2.15-2            (won't fix)  deb   CVE-2022-3715     Critical
```

Despite this issue being listed as fixed for bash 5.2.15-2: https://security-tracker.debian.org/tracker/CVE-2022-3715

Interestingly, debian:bookworm has the same bash version, and it passes all checks.

**Anything else we need to know?**:

**Environment**:
- Output of `grype version`:

```
Application:          grype
Version:              0.55.0
Syft Version:         v0.65.0
BuildDate:            2023-01-04T21:18:26Z
GitCommit:            c559833c7e02aed827773adb4f9677cb398577be
GitDescription:       v0.55.0
Platform:             darwin/arm64
GoVersion:            go1.18.9
Compiler:             gc
Supported DB Schema:  5
```

- OS (e.g: `cat /etc/os-release` or similar):

MacOS

**Comment by willmurphyscode** [comment]
Hi @zakandrewking,

I'm trying to understand exactly what's happening here. Here's what I think is happening:

1. You're starting with Debian 11 bullseye
2. You're adding the ability to install packages from Debian unstable
3. You're installing bash from the unstable channel of Debian, not from Debian 11

The reason you're seeing this vulnerability reported on the debian 11 image but not the debian 12 image is that Grype uses the distro information from `/etc/os-release` to filter the vulnerability database by namespace.

We can take a look in the database here:

``` sql
select id, package_name, namespace, version_constraint from vulnerability where namespace like "%debian%" and id = "CVE-2022-3715";'
id             package_name  namespace                      version_constraint
-------------  ------------  -----------------------------  ------------------
CVE-2022-3715  bash          debian:distro:debian:11
CVE-2022-3715  bash          debian:distro:debian:12        < 5.2-1
CVE-2022-3715  bash          debian:distro:debian:13        < 5.2-1
CVE-2022-3715  bash          debian:distro:debian:unstable  < 5.2-1
```

So when you're on a debian 12 image, bash 5.2.21 is considered fixed because it's greater than the version constraint, but when you're on debian 11, it's not, since no patch was issued for the debian 11 regular/stable bash.

I think we should investigate this type of cross-version install, to see if we can detect it.

**Comment by zakandrewking** [comment]
Thanks, that makes sense!!
