### ISSUE TITLE
Grype input with SPDX SBOM - report on wrong CVEs

### ISSUE THREAD

**Issue by rcohencyberarmor** [anchore/grype#1245]
**What happened**:
Generation CVEs of SBOM with 2 formats: json, spdx_json and got different result
image: quay.io/argoproj/argocd:v2.6.7

**What you expected to happen**:
the result of the 2 formats must be the same

**How to reproduce it (as minimally and precisely as possible)**:
./bin/syft quay.io/argoproj/argocd:v2.6.7 -o json --file jsonForamt.json
./bin/syft quay.io/argoproj/argocd:v2.6.7 -o spdx_json --file spdxForamt.json
./bin/grype jsonForamt.json != ./bin/grype spdxForamt.json

**Anything else we need to know?**:
the diff is happening on the golang package github.com/argoproj/argo-cd/v2:v0.0.0-20230323144144-5bcd846fa16e.

in the SPDX format we see that a CVE is **exist** on this package
in the JSON format we see that a CVE is **not exist** on this package

it is cause since the version of this package is pseudo version(vx.y.z-<timestamp>-<commit id>) and in the SPDX format we missed the metadata section under this package which give us the fixed version(which is v2.6.7), and in the json format the metadata section is exist , and therefore we not have the CVE there(in v2.6.7 is already fixed)
**Environment**:
- Output of `grype version`: v0.61.0
- OS: 
          NAME="Ubuntu"
          VERSION="20.04.4 LTS (Focal Fossa)"
          ID=ubuntu
          ID_LIKE=debian
          PRETTY_NAME="Ubuntu 20.04.4 LTS"
          VERSION_ID="20.04"

**Comment by tgerla** [comment]
Hi @rcohencyberarmor, thanks for the report. We're looking into this and we think we know why it is happening, but it will take a little bit more research for us to find a solution.

The general problem: there is a limitation in Go where we don't have a way to determine the version of the main Go package. This results in us matching against the vulnerabilities against all versions, since we don't know the actual version. 

This related issue is probably the preferred solution since it will minimize both false positives and false negatives: https://github.com/anchore/syft/issues/1785 -- but we will need to do some more investigation.

Additional notes for @anchore/tools: https://github.com/anchore/grype/blob/main/grype/matcher/golang/matcher.go#L48-L50 and https://github.com/anchore/grype/blob/main/grype/pkg/golang_metadata.go#L8 are relevant spots in the golang matching code.

**Comment by matthyx** [comment]
@tgerla are you sure it's the same issue?
From the report it looks related to the SBOM format used between `syft` and `grype` rather than a particular limitation in `syft`.

**Comment by wagoodman** [comment]
We may have misinterpreted the point your making, but I feel we're almost there.

Can you provide a few more details? Specifically:

1. What are a sample of CVEs in the **_SYFT JSON_** report that you expect should be there?
2. What are a sample of CVEs in the **_SPDX_** report that you expect should be there?
3. What are a sample of CVEs in the **_SYFT JSON_** report that you expect should **_NOT_** be there?
4. What are a sample of CVEs in the **_SPDX_** report that you expect should **_NOT_** be there?

We think it comes down to a) the pseudo version being used for matching and b) availability of the `mainModule` information only present in the syft JSON output.

**Comment by rcohencyberarmor** [comment]
Hi @wagoodman,
I expect those CVEs results to be the same if I just use different syft report format on the same image.
this is a image from the syft report with your own format (what I have called json format):
![image](https://github.com/anchore/grype/assets/84019060/18238c94-57ba-4624-a037-2a32affd9bfd)
and in the image we saw we have metadata section that with it we saw the real version of the go module and therefore we are seeing the right results.

this is a image from the syft report with SPDX format:
![image](https://github.com/anchore/grype/assets/84019060/aaa09dff-ff03-4cbb-9f66-ebc7b2b61177)
in this image we don't have metadata section and therefore we don't know the real golang package version and we add some CVEs that should not be there.

for example, those CVEs we should not see at all, since the version of the argo-cd is higher:
![image](https://github.com/anchore/grype/assets/84019060/b2367ec9-2c60-4707-b4f4-5a42bb78a213)

**Comment by wagoodman** [comment]
The thing that grype keys on in order to omit the CVEs you pointed out is in the syft json package object under `metadata.mainModule` (which has the value of `github.com/argoproj/argo-cd/v2`). The SPDX format does not have a way to express this field (`.metadata.mainModule`) so it is not included in the SBOM. 

So:

```
grype ./path/to/my.spdx.sbom
```
won't work, since grype is missing this information in order to exclude these results. That also explains why this works:

```
grype ./path/to/my.syft.sbom.json
```

This is the logic in grype today that uses this field to prevent doing matches that will most likely result in false positives: https://github.com/anchore/grype/blob/dc9bc1ee04492cebdac001bd0d4431cb39d015d8/grype/matcher/golang/matcher.go#L44-L51 .

**Comment by wagoodman** [comment]
I'm going to close this since this is really a format limitation of SPDX 2, not a bug in syft/grype -- this might change in SPDX 3, so I've made a placeholder issue when that format is implemented in syft (and thus grype can decode it) https://github.com/anchore/syft/issues/1970 .  

I think the best workaround is to use a format that captures this additional information, such as syft-json or CycloneDX for the meantime.
