### ISSUE TITLE
False Positive: CVE-2022-40705  

### ISSUE THREAD

**Issue by sekveaja** [anchore/grype#1248]
The current environment is running with cxf-rt-bindings-soap version 3.5.5,  but Grype is reported vulnerability CVE-2022-40705 which is Apache:soap.
That is completely different application. Therefore, it is a false positive.

**How to reproduce it (as minimally and precisely as possible)**:

Use cxf-rt-bindings-soap-3.5.5.jar as below.
```
            "package_cpe": "cpe:2.3:a:apache:cxf-rt-bindings-soap:3.5.5:::::::*",
            "package_cpe23": "cpe:2.3:a:apache:cxf-rt-bindings-soap:3.5.5:::::::*",
            "package_name": "cxf-rt-bindings-soap",
            "package_path": "/usr/src/app/BOOT-INF/lib/cxf-rt-bindings-soap-3.5.5.jar",
            "package_type": "java-archive",
            "package_version": "3.5.5",
            "severity": "High",
            "url": "https://nvd.nist.gov/vuln/detail/CVE-2022-40705",
            "vendor_data": [],
            "vuln": "CVE-2022-40705"
```

```
NVD link: https://nvd.nist.gov/vuln/detail/CVE-2022-40705
cpe:2.3:a:apache:soap:*:*:*:*:*:*:*:*   Show Matching CPE(s) | From (including)2.2
```

**Environment**:
```
Anchore Grype version: 0.61.0
- OS= "Ubuntu"
VERSION="20.04.3 LTS
cpe:2.3:a:apache:soap:*:*:*:*:*:*:*:*
   [Show Matching CPE(s)](https://nvd.nist.gov/vuln/detail/CVE-2022-40705#range-8371247)	From (including)
2.2
```

**Comment by willmurphyscode** [comment]
Hi @sekveaja,

Thanks for reporting this. Here are some quick repro steps to help us investigate:

```
wget 'https://repo1.maven.org/maven2/org/apache/cxf/cxf-rt-bindings-soap/3.5.5/cxf-rt-bindings-soap-3.5.5.jar'
grype cxf-rt-bindings-soap-3.5.5.jar 
```

which prints

```
cxf-rt-bindings-soap  3.5.5                java-archive  CVE-2022-40705  High   
```

And here's some information from the match details:

CVE-2022-40705 from https://nvd.nist.gov/vuln/detail/CVE-2022-40705
matched artifact is:
   cxf-rt-bindings-soap - pkg:maven/org.apache.cxf/cxf-rt-bindings-soap@3.5.5
match type is cpe-match
CPEs 
  - `cpe:2.3:a:apache:cxf-rt-bindings-soap:3.5.5:*:*:*:*:*:*:*`
  - `cpe:2.3:a:apache:cxf_rt_bindings_soap:3.5.5:*:*:*:*:*:*:*`
  - `cpe:2.3:a:apache:soap:3.5.5:*:*:*:*:*:*:*`
  - `cpe:2.3:a:apache:cxf:3.5.5:*:*:*:*:*:*:*`

URLs:
  - https://nvd.nist.gov/vuln/detail/CVE-2022-40705
  - http://www.openwall.com/lists/oss-security/2022/09/22/1
  - https://lists.apache.org/thread/02yo04w93rdjmllz4454lvodn5xzhwhl


I think `cpe:2.3:a:apache:soap:3.5.5:*:*:*:*:*:*:*` is generated by grype and matches https://nvd.nist.gov/vuln/detail/CVE-2022-40705#range-8371247, so I think this is due to grype generating too broad a CPE from the detected package. I'm adding a label for this type of issue so that we can try to work on the entire class of issue.

**Comment by willmurphyscode** [comment]
Hi @sekveaja,

This was because Grype previously used CPEs for matching JARs, but by default now uses PURLs, which reduces the odds of this sort of cross-application confusion:

``` sh
wget -q 'https://repo1.maven.org/maven2/org/apache/cxf/cxf-rt-bindings-soap/3.5.5/cxf-rt-bindings-soap-3.5.5.jar'
grype -q cxf-rt-bindings-soap-3.5.5.jar
No vulnerabilities found
``` 

I'm closing this, since the vulnerability is no longer reported, but please let us know if we've missed something.
