### ISSUE TITLE
Filter out packages that are owned by OS packages (ownership overlap)

### ISSUE THREAD

**Issue by wagoodman** [anchore/grype#1373]
**What would you like to be added**:
Today we conditionally filter out packages that are owned by other packages before attempting to find matches https://github.com/anchore/grype/blob/bc93a968b539395fa11517897a629cca454d97e2/grype/pkg/package.go#L104-L144 .

Ideally we would remove packages that overlap in ownership with other packages when the parent package is an OS package.

**Why is this needed**:
This should remove a class of false positives since OS distributions typically manage back ports of fixes and are the source of truth for the logical package, thus should override any vulnerability match claims for the contained packages (e.g. if an RPM contains a python package and we find a vuln for the python package and not the RPM, we should drop this).

Dev notes:
- we do something like this today (see the above link) so it would be ideal to stay consistent here: try to filter out the package based on artifact/relationship rules before we do any matching.

**Comment by kzantow** [comment]
This is related to https://github.com/anchore/syft/issues/931

**Comment by willmurphyscode** [comment]
Found an example case where I'm not sure the RPM package should have won over the python package: Language packages that are available from the OS package manager. For example, in the branch where I have this feature partly built, we can see: `pkg:rpm/rhel/python3-six@1.11.0-8.el8?arch=noarch&upstream=python-six-1.11.0-8.el8.src.rpm&distro=rhel-8.3` is preferred over `pkg:pypi/six@1.11.0`.

It's likely there because someone ran `yum install -y python3-six`, but any vulnerabilities reported against the PyPI version of the package should probably be reported by grype, so it's not obvious in this case that preferring the OS package is the right thing to do.

**Comment by westonsteimel** [comment]
Actually these are exactly the cases where we want the os packages to win out because rhel backport fixes that PyPI won't know about.

**Comment by westonsteimel** [comment]
Now something which would be even more accurate here would be to somehow deselect PyPI vulns specifically when a RHEL one overrules it, but that gets much more complicated because right now grype only knows how to fetch vulnerabilities that a package may be affected by and that approach would require fetching ones that a package is not affected by.  It'd also require looking at the relatedVulnerability data to convert identifiers so that you could compare between say GHSA and CVE.  It might be doable though, but probably needs alot more thought

**Comment by westonsteimel** [comment]
Also I don't think we could do that approach today since grypedb might not even have records when something is marked as not affected or withdrawn, and those would be important to capture somewhere if attempting the more advanced approach

**Comment by willmurphyscode** [comment]
Thanks for the additional context @westonsteimel. Based on that additional info, I'll keep trying to get #1387 merged. I may have found an interesting edge case with the quality gate, which I'll discuss on the PR.

**Comment by willmurphyscode** [comment]
@westonsteimel and I discussed this issue this morning, and I think there are basically 2 approaches, which I'll explain with an example issue:

## Example situation
```
syft -q docker.io/anchore/test_images@sha256:c8d664b0e728d52f57eeb98ed1899c16d3b265f02ddfb41303d7a16c31e0b0f1 | grep guava
guava                                    20.0                                            java-archive
guava20                                  20.0-8.module+el8+5161+5cac467c                 rpm
```

In this case, `syft` found 2 packages with `guava` in the name: the JAR `guava`, and the rpm `guava20`. They have slightly different versions. The guava20 RPM has a more specific version number, because we have the RPM installed package database to look at. But these are the same package; the Java cataloger found the JAR, and the RPM cataloger found the RPM.

Let's see what grype thinks:

```
grype -q docker.io/anchore/test_images@sha256:c8d664b0e728d52f57eeb98ed1899c16d3b265f02ddfb41303d7a16c31e0b0f1 | grep guava
guava                                    20.0                                                                                               java-archive  CVE-2023-2976        High
guava                                    20.0                                           24.1.1                                              java-archive  GHSA-mvr2-9pj6-7w5j  Medium
guava                                    20.0                                           32.0.0                                              java-archive  GHSA-7g45-4rm6-3mm3  Medium
guava                                    20.0                                                                                               java-archive  CVE-2018-10237       Medium
guava                                    20.0                                                                                               java-archive  GHSA-5mg8-w23w-74h3  Low
guava                                    20.0                                                                                               java-archive  CVE-2020-8908        Low
```

We can see that all the vulnerabilities are reported against the JAR, not the RPM. So there are two possibilities: either the RPM has a distro-specific fix that we know about, or the distro doesn't report the package as vulnerable. This brings us to the two approaches:

## First approach: remove before matching

In this approach, we remove the JAR `guava@20` before matching. Then none of the above vulnerabilities are found. If we believed that the distro's vulnerability feed were exhaustive, this would be a great approach. It's what's suggested earlier in this issue, and it's certainly easier to implement.

However, there are 3 possible situations:

1. Distro feed had no record - we don't know whether we should have removed the JAR
2. Distro feed was vulnerable - removing the JAR was fine, since we're report against the RPM, which has more specific version info anyway.
3. Distro feed had a specific fix information - removing the JAR was correct, since the report against the JAR was a false positive caused by not considering the OS specific fix.

## Second possible approach

In the second approach, we try to figure out which of the 3 possible situations we're in, and act accordingly:

1. Distro feed has no record - leave the vuln reported against the JAR, because a false positive is better than a false negative.
2. Distro feed shows OS package is vulnerable - remove the match against the JAR, because the vulnerability is redundant
3. Distro feed shows OS package is fixed - remove the match against the JAR, because it is a known false positive.

I'm going to take some time to see how hard implementing the second approach is.

**Comment by willmurphyscode** [comment]
I've done some research on the second approach, and it requires changing grype a bit.

In order to be able to correctly dedupe in this way, we need a place in the code where we have the following information:
1. We know whether a given package is owned by an OS package, in other words, the SBOM's relationships are in scope
2. We know whether the OS package is vulnerable, in other words, matching has taken place
3. If the OS package is not vulnerable, we know whether it's because distro has no vulnerability record, or because the distro reports the package as not affected or patched. In other words, the vulnerability store is in scope*.

Right now, the only place where all this information is in scope is at https://github.com/anchore/grype/blob/fff434156cb7f9415ad51306f95cb2fc2d38e129/cmd/grype/cli/legacy/root.go#L367, which has the matches, the relationships (on the SBOM), and the vulnerability store. However, it seems strange to have additional filtering of matches after the main `vulnerabilityMatcher.FindMatches` call, so I think the vulnerability matcher struct (`grype.VulnerabilityMatcher`) should be updated to have a pointer to the SBOM. The code should check for nil on the vulnerability matcher struct, since library users might not know to set the new field.

I'll take this specific approach and see how far it gets me:

1. Change https://github.com/anchore/grype/blob/fff434156cb7f9415ad51306f95cb2fc2d38e129/grype/vulnerability_matcher.go#L15-L21 to have a pointer to a syft sbom.SBOM on it.
2. Change https://github.com/anchore/grype/blob/fff434156cb7f9415ad51306f95cb2fc2d38e129/grype/vulnerability_matcher.go#L45-L70 to use that reference to deduplicate as described in "Second possible approach" in my last comment

**Comment by willmurphyscode** [comment]
I think rather than block this issue on #1426, we might do the following:

1. Have an allow-list of vulnerability feeds that are believed to be "complete." That is, vulnerability feeds that report both fixed and non-fixed vulnerabilities
2. For OS packages that are from a distro operating one of those feeds, remove the non-OS package from the ownership-by-overlap relationship before matching.

For example, if we're scanning an RHEL8 image, and we have an RPM that owns a Python package, go ahead and remove the Python package before matching, since the RHEL8 feed will have better information on whether the package is vulnerable than GHSA will. But if we're scanning an Alpine image and there's an APK that owns a Python package, leave the python package under consideration for matching, because Alpine only reports fixes, and so the matching GHSA or NVD data directly is necessary to detect vulnerabilities that Alpine hasn't released a patch for yet. Then, when #1426 is implemented, we can remove the allow-list in favor of the logic described in the previous comment.

Next steps are:

1. Develop this allow list
2. Update https://github.com/anchore/grype/pull/1387/files#diff-c1eeca4b68c3cef87a8131f596f5e598d5b9a56704624ff94afd7db799e4193aR142 to only filter packages if the distro is allowed by that allow-list.
