### ISSUE TITLE
Cannot concurrently access sqlite DB within a single process

### ISSUE THREAD

**Issue by wagoodman** [anchore/grype#155]
**What happened**:
When deving a new feature that uses the metadata provider concurrently I saw this:
```
[0001] ERROR unable to show grype-vulnerability-scanning-finished event: unable to show vulnerability report: unable to fetch vuln="CVE-2020-13777" metadata: metadata provider failed to fetch id='CVE-2020-13777' recordsource='vulnerabilities:ubuntu:20.04': unable to query: trying to lock a locked lock
```

Which is from the sqlite reader implementation used (sqlittle): https://github.com/alicebob/sqlittle/blob/528efd88f2215b063713bdf694033d8ef488aaaa/db/pager_unix.go#L57

**What you expected to happen**:
Since grype is read-only, grype should be able to hold a shared lock without affecting other readers.

**How to reproduce it (as minimally and precisely as possible)**:
Attempt to use the `vulnerability.MetadataProvider` concurrently.

**Comment by luhring** [comment]
At this point, it looks like no issue is present when multiple `grype` processes access the database concurrently. To test this, I performed the following steps:

1. In GoLand, I opened the grype project and placed a breakpoint here: https://github.com/anchore/grype/blob/main/grype/matcher/controller.go#L83.
1. I ran grype in debug mode and waited for the program to break at the line above.
1. From a terminal, I ran `grype ...`. No error was observed.

This finding deescalates this issue for the team for now. It would be much more problemmatic if two grype processes could not safely coexist on a single system (e.g. if two CI jobs were running on a host (non-containerized) at the same time.

We'll leave this issue open, because we still need to explore how a single grype process can safely use the sqlite database concurrently (e.g. among multiple goroutines).

**Comment by tonykay** [comment]
So running the latest and greatest `0.32.0` on Mac M1 Monterey 12.3 (ie Beta). I see the above type error message. I updated the database. I brew uninstall grype and reinstall and still see failures:

```
grype nextcloud | tee ~/Downloads/nextcloud.txt
 ✔ Vulnerability DB        [no update available]
 ✔ Loaded image
 ✔ Parsed image
 ✔ Cataloged packages      [317 packages]
 ✔ Scanned image           [371 vulnerabilities]

[0071] ERROR unable to show grype-vulnerability-scanning-finished event: unable to show vulnerability report: unable to fetch vuln="CVE-2021-28831" metadata: metadata provider failed to fetch id='CVE-2021-28831' recordsource='debian:11': unable to query: mmap: invalid ReadAt offset 603688960
```

Happy to test any fixes, recommendations.

**Comment by cpendery** [comment]
The switch over to using Gorm around 0.34.0 (I can't find which release the change was made rn) fixed this issue. I can currently access the database using the Grype apis with no issues. @spiffcs I think this can be closed
