### ISSUE TITLE
Build Docker Image with Database Packaged

### ISSUE THREAD

**Issue by kchason** [anchore/grype#1652]
**What would you like to be added**:

A Docker image that has the database packaged into the image and disables the automatic update by default.

**Why is this needed**:

The offline/air-gapped instructions still require the database to be hosted or sideloaded. This is an extra step versus downloading and copying a Docker image to an offline environment.

**Additional context**:

There is a pull request with this capability using the `packaged` suffix (similar to the `debug` one) at https://github.com/anchore/grype/pull/1653.

**Comment by wagoodman** [comment]
Adding this image wouldn't be as beneficial as it initially appears. Grype has a default configuration to fail when the DB is > 5 days old to ensure that users do not use old DBs by default. For this reason we would need to publish images nearly daily to ensure that users have the most up to data DB (which is much more frequently than we're releasing today). This means for an air-gapped solution, the DB would either need to be pulled often anyway or the configuration changed to a longer stale period for the DB age.

Alternatively, when preparing the image for transfer to air-gapped systems, you could build your own image easily in an ad-hoc way:

```dockerfile
FROM anchore/grype:latest

# disable auto updating the DB
ENV GRYPE_DB_AUTO_UPDATE false

# set this to what you need in hours
ENV GRYPE_DB_MAX_ALLOWED_BUILT_AGE 120h

RUN ["/grype", "db", "update"]
```

```
$ docker build -t grype-with-db:latest .
$ docker run --rm -it grype-with-db:latest alpine:latest
 ✔ Parsed image                                                                                                                        sha256:1dc785547989b0db1c3cd9949c57574393e69bea98bfe044b0588e24721aa402
 ✔ Scanned for vulnerabilities     [14 vulnerability matches]
   ├── by severity: 0 critical, 0 high, 12 medium, 0 low, 0 negligible (2 unknown)
   └── by status:   2 fixed, 12 not-fixed, 0 ignored
NAME           INSTALLED   FIXED-IN  TYPE  VULNERABILITY   SEVERITY
busybox        1.36.1-r15            apk   CVE-2023-42366  Medium
busybox        1.36.1-r15            apk   CVE-2023-42365  Medium
busybox        1.36.1-r15            apk   CVE-2023-42364  Medium
busybox        1.36.1-r15            apk   CVE-2023-42363  Medium
busybox-binsh  1.36.1-r15            apk   CVE-2023-42366  Medium
busybox-binsh  1.36.1-r15            apk   CVE-2023-42365  Medium
busybox-binsh  1.36.1-r15            apk   CVE-2023-42364  Medium
busybox-binsh  1.36.1-r15            apk   CVE-2023-42363  Medium
libcrypto3     3.1.4-r2    3.1.4-r3  apk   CVE-2023-6129   Unknown
libssl3        3.1.4-r2    3.1.4-r3  apk   CVE-2023-6129   Unknown
ssl_client     1.36.1-r15            apk   CVE-2023-42366  Medium
ssl_client     1.36.1-r15            apk   CVE-2023-42365  Medium
ssl_client     1.36.1-r15            apk   CVE-2023-42364  Medium
ssl_client     1.36.1-r15            apk   CVE-2023-42363  Medium
```

I'm going to close this and the PR for now since there is an easy workaround for this and there are aspects of the image distribution that don't make sense with the default configuration of grype.

**Comment by StianOvrevage** [comment]
I've created regular builds of `grype` with bundled database as well as compression: https://github.com/StianOvrevage/grype-with-db/

    docker run --rm -it stianovrevage/grype-with-db alpine:latest
