### ISSUE TITLE
Add details of "wont-fix" state

### ISSUE THREAD

**Issue by eram** [anchore/grype#1717]
**What would you like to be added**:
Currently, some vulnerabilities are marked with `fix.state="wont-fix"`. I'd like any references to advisories suggesting the vulnerability is a false-positive would be added, possibly under the `advisories` array. This should include a reasonning message and source/author.

**Why is this needed**:
It is unclear how and why this "decision" that a vulnerability is a false-positive was made. Where did the "wont-fix" come from and who made the decision? Was it made in the context of the specific image, or what.

**Additional context**:
I would expect a short VEX entry to be added to the CycloneDX vulnerability analysis object as well - https://cyclonedx.org/docs/1.5/json/#vulnerabilities_items_analysis_state
Related issue: https://github.com/anchore/grype/issues/386

**Comment by kzantow** [comment]
Hi @eram, after another read I'd like to just clarify what "won't fix" means: this is not a determination that Grype is arbitrarily making, it's the status of the vulnerability according to the maintainer(s), or at least that's what it's supposed to be. Let's say a package in Debian 1 is vulnerable, this information makes its way into a vulnerability tracker, but Debian has moved on and is no longer actively maintaining Debian 1 and will not make further changes because it's just too old -- the maintainers can indicate that they "won't fix" the vulnerability. This is decidedly different than a "false positive". A false positive would be a match indicating a package _is vulnerable when it is not, in fact, vulnerable_.

That said, what information specifically would you be looking for? We should be providing links back to NVD or other issue trackers as long as that's available, which generally could have information about related discussions such as why something wouldn't be fixed. Is there some structured data you're looking to expose that we just aren't today? Are there some specific examples of these "won't fix" entries that seem to be obtuse and you could provide some CVE numbers to look at what data we have available?

**Comment by tgerla** [comment]
Since we haven't heard back, I'll close this issue but please feel free to re-open if you are still interested in working on this. Thanks!
