### ISSUE TITLE
CycloneDX output `metadata.properties` set to `null` instead of empty array or omitted.

### ISSUE THREAD

**Issue by Cerebus** [anchore/grype#1759]
**What happened**:

```
> grype -o cyclonedx-json python:3.12.2-slim > test-grype.json
> check-jsonschema --schemafile ./schema/bom-1.5.schema.json test-grype.json
Schema validation errors were encountered.
  test-grype.json::$.metadata.properties: None is not of type 'array'
```

**What you expected to happen**:
It should validate.  E.g., after replacing `metadata.properties: null` with `[]`:

```
> check-jsonschema --schemafile ./schema/bom-1.5.schema.json test-grype.json
ok -- validation done
```

**How to reproduce it (as minimally and precisely as possible)**:

See above.

**Anything else we need to know?**:

**Environment**:
Application:         grype
Version:             0.74.7
BuildDate:           2024-02-26T17:30:31Z
GitCommit:           brew
GitDescription:      [not provided]
Platform:            darwin/amd64
GoVersion:           go1.22.0
Compiler:            gc
Syft Version:        v0.105.1
Supported DB Schema: 5

**Comment by tgerla** [comment]
Hi @Cerebus, thank you for the report! We'll get this taken care of as soon as we can.

**Comment by wagoodman** [comment]
this is in the category of ensuring that all collections like this are allocated (currently this is `omitempy`)

**Comment by lucasrod16** [comment]
Hi @tgerla @wagoodman,

I am interested in working on this. It appears that the `metadata.properties` field gets initialized as a pointer that points to a nil slice, causing the `null` value.

It happens when [`ToFormatModel` is called in the cyclonedx presenter](https://github.com/anchore/grype/blob/e7ceffadc856ce70b2854eefa3fc78f8770365e7/grype/presenter/cyclonedx/presenter.go#L59), which ultimately calls `toBomProperties`. In `toBomProperties`, [`EncodeProperties` returns a `nil` props slice and is returned as `&props` resulting in an initialized pointer with a nil slice as a value](https://github.com/anchore/syft/blob/3161e1847efab3815b51eceb2f1a81cd8944eb34/syft/format/common/cyclonedxhelpers/to_format_model.go#L213-L214).

I have two potential solutions that I'd appreciate your feedback on before submitting a PR:

1. Set the `metadata.properties` field in grype to work around this behavior

```go
cyclonedxBOM.Metadata.Properties = &[]cyclonedx.Property{} // populates the properties field as an empty array []
cyclonedxBOM.Metadata.Properties = nil // properties field does not get encoded
```

2. Add a `nil` check in syft to prevent returning an initialized pointer with a nil slice value

```go
func toBomProperties(srcMetadata source.Description) *[]cyclonedx.Property {
	metadata, ok := srcMetadata.Metadata.(source.ImageMetadata)
	if ok {
		props := helpers.EncodeProperties(metadata.Labels, "syft:image:labels")
		if props == nil {
			return nil
		}
		return &props
	}
	return nil
}
```

I’m happy to implement either solution. Thanks!

**Comment by lucasrod16** [comment]
It's also worth noting that the `cyclonedx-go` maintainers have a desire to move away from using slice pointers. Removing usage of slice pointers upstream would be an ideal solution and would make issues like this less likely. Unfortunately I do not understand the XML parsing limitations well enough to contribute much to a solution at this point.

https://github.com/CycloneDX/cyclonedx-go/issues/21

**Comment by kzantow** [comment]
@lucasrod16 it looks like the [properties are optional](https://cyclonedx.org/docs/1.6/json/#metadata), I'd opt for option 2, returning an accurate `nil` value

**Comment by lucasrod16** [comment]
@kzantow I have opened a PR to syft to return a `nil` value in `toBomProperties` https://github.com/anchore/syft/pull/3119
