### ISSUE TITLE
How to output ANSI colors

### ISSUE THREAD

**Issue by DavidPerezIngeniero** [anchore/grype#1790]
**What would you like to be added**:

When invoked from the command line,  ANSI colors are used and it is easier to understand the data visually

When called from a bash script in a Jenkins, no colors are shown.

**Why is this needed**:

More clarity.

**Additional context**:
Linux.
grype 0.75.0

**Comment by willmurphyscode** [comment]
Hi @DavidPerezIngeniero,

You can set `CLICOLOR_FORCE=true` in the environment to force Grype to color the output even in non-TTY invocations, though you might see some unexpected behavior depending on what shell control characters as supported in your Jenkins environment.

By design, Grype detects that it's being run outside a TTY and doesn't color output (or generate the progress bars or anything) because it thinks it's being redirected to a file, or to another program that won't know how to interpret the control characters. This is why, for example `grype <something> | grep <some pattern>` works without `<some pattern>` needing to know about the bytes that tell the shell to change color. 

Please let us know if this doesn't solve your problem.
