### ISSUE TITLE
Exclusion option for files and folders

### ISSUE THREAD

**Issue by Karreg** [anchore/grype#183]
**What would you like to be added**:

An option to exclude files and folders

**Why is this needed**:

In the context of scanning in a container, for example in GitLab-CI, without privileged mode of the underlying docker and DinD, there are 2 options :
* Pulling the image with podman, but it's time and disk consuming. Not an acceptable option
* Scan the image from the image itself, but in the case of GitLab, the repository will be mounted in `/builds` and it should not be scanned.

So the best option is to scan the image from the image itself, by excluding the repository clone.

**Comment by wagoodman** [comment]
Hey @Karreg ! It sounds like you already have a running container made from the image you would like to scan and that grype is already available inside this container, yes? If so, having an "exclude path" option makes a lot of sense. 

The simplest case could be a flag, which works when scanning directories and images:
```
# your use case
grype --exclude-path /builds  dir:/

# scan an image, and exclude multiple paths
grype --exclude-path /a/path --exclude-path /another/path  docker:some/image:latest
```

But we could also expose this option as a config option (additionally):
```
# .grype.yaml within the root of your repo
exclude-paths:
- /builds
- /some/other/path
# we could also allow for globs potentially?
- **/node_modules/**/package.json
```

and invoke grype like so:
```
# the scan would ignore all paths listed in the config
grype -c /builds/.grype.yaml /
```

The above is just a proposal --open to other options here!

I've made a matching issue in syft to capture this, as much of the additional behavior would need to be implemented there for grype to leverage it.

cc: @anchore/toolbox

**Comment by Karreg** [comment]
Hello,

Yes that's exactly the use case and need.

`--exclude-path` is fine. My use case is only on folders, maybe a later improvement could use regex on files like `--exclude-path "/path/to/folder/**/*.lock"`?

Exposing it as a config option makes sense with what is done today, but it's not my use case either. I don't use config file, environment variables are more useful in a CI context. By the way, it would be a great third option to configure grype...

**Comment by wagoodman** [comment]
Agreed on the `glob` case (`/path/to/folder/**/*.lock`), would be simple to add and pretty useful for ignoring a class-of-things instead of just a static location.

Today most config items can also be overridden/provided by environment variables, for instance:
```
# config
db:
  auto-update: false
```
... is the same as:
```
GRYPE_DB_AUTO_UPDATE=false grype my/image:latest
```
(we should add a note in the readme that explicitly lists this feature.)

**Comment by Karreg** [comment]
Yes, it should be great to have them documented in some way. Without documentation, the only option is to look at the source code :)

**Comment by Karreg** [comment]
Hello,

Is there any change on this matter? Is it still being looked at?

**Comment by Karreg** [comment]
I would be happy to do PRs, but I'm not knowledgeable in all the needed languages... I did some in anchore inline scanner a long time ago :)

About your feature, I would say it depends. I had a look at the issue, and I'm not sure about what it does:

Does this feature rely on docker daemon? It looks like it's not the case.
  * If yes, I doubt it won't help as it will required privileged gitlab runner, which comes with security issues. That's why I'm using podman (until I can scan an image from within itself. see #326)
  * If no, it would fit for sure. But I guess in this case it will download the layers directly as tarball, and it will come with the same space issue I'm currently having with podman

**Comment by luhring** [comment]
>Does this feature rely on docker daemon?

No, it doesn't. Grype will look for the Docker daemon, but it will access the registry directly if the daemon's not available.

And further, you can tell Grype explicitly to use only the registry but pretending your image string with the `registry:` scheme. For example, if you ran `grype registry:ubuntu:latest`, Grype would immediately access the registry (in this case, the registry is implicitly `index.docker.io`) to pull the image, and it wouldn't have any interaction with the Docker daemon.

>it will come with the same space issue I'm currently having with podman

Can you clarify what this issue is for me? Or if you've already described it somewhere, point me there? I want to better understand the circumstances of when `registry:` is not a good solution for users.

**Comment by Karreg** [comment]
Sure.

So, I'm trying to execute the scan in a container, on an unprivileged gitlab-runner. Meaning the docker daemon is not available, and aufs can't be used.

aufs is the default docker layer filesystem, where each layer only store the diff with the previous layer.

on unprivileged runner, you can use docker, but you can use podman. And when aufs is not available, the fallback driver is vfs, where each layer is stored as a whole layer. this is when it causes issues: 

Each layer is a full image.
Your image will use (layer count) * (image size) MB of disk.
Since our gitlab-runner can't use more than 40 GB, you can quickly fill it up with big image with a few layers (who said Android?), or smaller images with a lot of layers (yes, that's not a good practice, but we don't have hand on it).

So this is what happens here currently with grype. Since we can scan an image from itself, we have to rely on podman to pull image and save it as a tarball...

Maybe you work differently, only working on each layer tarball separately, and that would be great news. but since a layer can remove something from the previous layer, I don't know how you handle that.

I hope this won't be an issue :)

**Comment by luhring** [comment]
Thank you for the context!

If the objective is to use Grype to scan a container image, what is the need for docker/podman/aufs/vfs? None of those come into play when Grype scans a container image.

Re: "Docker", the Docker **client** is certainly not needed, whereas the Docker **daemon** _can_ be used, but isn't necessary here since Grype can talk to a remote registry directly.

To have Grype pull an image directly from a registry, you **will need** enough available disk space to accommodate the size of the image. So if you have 30 GB free, but your image is 32 GB, Grype won't work (and actually, no local scanner will work).

One thing to note: Grype doesn't keep images on disk after it's finished scanning. So you shouldn't need to worry about accumulating images over time.

**Comment by Karreg** [comment]
You need the image to scan it. Either you scan it from itself, or your scan it after downloading it, or have I missed another option?

Of course you can't scan an image that is bigger than the disk you have, but it's not the issue here. The issue is that to scan the image, I need to pull it, with podman and vfs as there's no other option in an unprivileged gitlab-runner with docker executor. An image taking 5 GB with 10 layers will take up to 55 GB of disk space in this case.

If docker/podman is of no use, I will try right away to scan an image from an OS with no podman/docker. That would be good news, but I thought from your saying it was being developped with GitLab... Let me check :)

**Comment by Karreg** [comment]
Damn. It was that easy...
I just missed one thing: you actually have added this feature, and that's what your have written, but in the late day, I have read that you were working on it.

So that's perfect to me, great job! :)

I guess this issue is now irrelevant. Thanks!

**Comment by luhring** [comment]
>So that's perfect to me, great job! :)

Glad to hear it!

Also, we could still leave this issue open, since it's not a bad feature idea.

**Comment by luhring** [comment]
"Why did I change this title?"

My thinking: The root issue here seemed to be support within a GitLab CI/CD workflow. While file/folder exclusions was one implementation that would address it, the support for registry-based scans also addresses it (as evidenced by the user closing the issue).

We've just had a new submission for file/folder exclusions (#389), and while normally I would close it as a duplicate of this issue, this issue ended up reflecting a slightly different problem and solution, and so I've updated its title to reflect that, which will make it easier for us to understand the needs of the open issues in a list based on their titles.
