### ISSUE TITLE
List only vulnerabilities from a level and above

### ISSUE THREAD

**Issue by pantelis-karamolegkos** [anchore/grype#1892]
**What would you like to be added**:

Option for showing / listing only vulnerabilities above a threshold severity level

**Why is this needed**:

To reduce noise output.

**Additional context**:

**Comment by tgerla** [comment]
Hey @pantelis-karamolegkos, thank you for the suggestion. I think this issue is similar to: https://github.com/anchore/grype/issues/1612 -- this issue is in our backlog for future implementation. If you're interested in working on it, definitely let us know and we can help you get started. There is also https://github.com/anchore/grype/issues/1378 which is related to severity.

Another solution might be to use a custom template to filter out low priority vulnerabilities (or any other criteria): https://github.com/anchore/grype/tree/main/templates#html -- check out the last section which implements this for HTML output.

**Comment by kzantow** [comment]
Note this may be a duplicate or special case of: https://github.com/anchore/grype/issues/197

**Comment by spiffcs** [comment]
Were talking about this in discourse!

Come add your thoughts here:
https://anchorecommunity.discourse.group/t/how-can-we-make-grypes-output-more-focused/57

**Comment by kzantow** [comment]
Hi, I think since this is a duplicate we're going to close it in favor of the older issue ([197](https://github.com/anchore/grype/issues/197)) but please do follow and vote there with reactions!
