### ISSUE TITLE
"omitempty" marshaling makes integration efforts harder

### ISSUE THREAD

**Issue by alfredodeza** [anchore/grype#190]
**What happened**: In Javascript integrations that are consuming the JSON output of `grype`, there is a lot of accessing object attributes that have potential for not being present. One of these attributes (in vulnerabilities) is `Links`. 

Most of all the vulnerabilities will have at least 1 link. This is similar to https://github.com/anchore/grype/issues/189 where integrations are expecting this value to always be there. 

I understand that it isn't feasible to add empty values to all attributes for the sake of making it easier for integrations (would bloat the JSON output), but I think it is reasonable to avoid the `omitempty` option on most of the vulnerability reporting (specifically for JSON). 

JSON reporting is meant for machine-consumable workflows, so bloating with (some) empty values doesn't seem too bad.

**What you expected to happen**: Reduce the amount of `omitempty` options in JSON tags when reporting vulnerabilities. Although https://github.com/anchore/grype/issues/189 should take care of handling the `Links` attribute, this still makes other integrations harder.

**How to reproduce it (as minimally and precisely as possible)**: Nothing to reproduce, it just makes it harder to work with in JS :) 

**Anything else we need to know?**: Related to https://github.com/anchore/scan-action/issues/68

**Environment**:
- Output of `grype version`:
- OS (e.g: `cat /etc/os-release` or similar):

**Comment by luhring** [comment]
Just weighing in to say I second this idea — when other applications need to consume our data, the more predictability there is in the data structure, the better. And for the JS case in particular, I can attest to how bug-prone it is to try to keep track of and properly handle all potentially `undefined` fields.

**Comment by wagoodman** [comment]
I agree with you both. For both syft and grype we should start getting to a rule of thumb for what fields get conditionally omitted vs are always present. Integrations will always need to safely access each json field as we cannot guarantee every field is present for reasons such as:

- There are fields in which their lack of presence indicates a non-existent value (different than a positively found empty value).
- Fields which data shape are dynamic (e.g. `map[string]string` or `map[string]map[string]string`)

To aid in this, integrations should use utilities such as [jsdig](https://www.npmjs.com/package/jsdig) or other helper functions to do such json parsing safely.

For a starting point, lets consider the following as rules of thumb for when to always persist vs conditionally omit fields:

1. **Always persist** slice/array (`[]`) and maps (`{}`) as empty, allocated values. That is, never allow for a `nil` value, and if the backing collection is empty, represent that with `[]` or `{}`. E.g. always persist https://github.com/anchore/syft/blob/main/syft/pkg/apk_metadata.go#L26 .

2. **Conditionally omit** entire structs where the underlying data does not exist. E.g. conditionally omit https://github.com/anchore/syft/blob/main/syft/pkg/python_package_metadata.go#L11 , where the underlying digest record is an optional field.

3. **Always persist** fundamental literal fields (numbers and strings), except those fields which REQUIRE a non-existant state.

**Comment by luhring** [comment]
I like the idea of a standard approach for the sake of consistency. There are some things to keep in mind, though.

In JSON, "missing properties" is not synonymous with "missing property values". The former has more severe consequences, since we're dealing with the type itself changing with the inclusion or exclusion of properties.

In general, it seems like what we want for a `nil` value in the Go struct is a `null` value in the JSON object. This sends a semantically equivalent message — "yes, that property is part of this type, and you were right to access it, but on this particular object instance, no usable value is present."

This is different altogether from when we use `omitempty`, which divides the Go struct and the JSON object into two differing interpretations of the data.

If a value can be `null`, it's still important to detect and adapt to that condition. But using `null` instead of an undefined property rules out type errors on the root object in question, which is noteworthy.

As an exception to this, I agree with using a JSON empty array (`[]`) where in Go there's a `nil` value with slice type. This is semantically equivalent. (Go's use of `nil` here is a product of the slice abstraction.)

I would caution us from using empty object values (`{}`) to signal an absence of data in JSON. I can't think of a worthwhile JS operation that becomes easier due to this, and it actually makes it more difficult to detect that no data is present.

Go's `map` type is interesting, since it's used in different ways in different contexts. Sometimes, it functions kind of like a Python `dict`, which is like an `object` in JS. But not always — and in fact, using it in this way makes it harder for the consumer to deal with the object's type, since the set of properties can be dynamic.

Sometimes, `map` is used to store a _set_ of things. Here, the `map` type might be useful in Go since it natively prevents multiple collection members from sharing the same "key" value. But in JSON, that functionality might not be useful, and it could make more sense to use an `array` in some cases.

**Comment by luhring** [comment]
Following in @wagoodman's footsteps, here's a set of proposed guidelines that optimizes for the ease of consuming our JSON data safely.

1. Never use `omitempty`.

1. For **non-pointer types**, marshal values in the "obvious" way _(i.e. `string` to `string`, `int`-types and `float`-types to `number`, `bool` to `boolean`, `struct`-types to `object`, etc.)_. One allowable exception to this is when dealing with `enum`-like Go types; for example, where a custom Go type was based on `int` (and perhaps initialized with `iota`), but a `string` JSON value is more consumer-friendly, and string values map 1-to-1 in a predictable manner to the underlying `int` values.

1. For **slice types**, marshal `nil` to an empty array (`[]`).

1. For **map types**, consider if the map in question behaves more like an object or like a collection (i.e. array). If the set of possible map keys is not predictable by the consumer, the data would more easily be consumed as an array. For `nil` maps, marshal "object-like" map values to `null`, and "collection-like" map values to an empty array (`[]`).

1. For all other **pointer types**, marshal `nil` to `null`.

1. If for any part of the JSON output, `null` seems like it shouldn't be a possible value, consider whether the underlying variable needs to be a pointer type. If it does, consider gracefully dereferencing the value upon marshaling.

**Comment by wagoodman** [comment]
I'd vote we do two things:

1. For syft/grype: use the suggestions @luhring outlined in https://github.com/anchore/grype/issues/190#issuecomment-721193650

2. For integrations: be pessimistic about data existence/access and use tooling such as ruby's `dig`, in javascript [`jsdig`](https://www.npmjs.com/package/jsdig), etc... consider safe defaults when data is missing or short-circuit if absolutely necessary.

**Comment by alfredodeza** [comment]
I don't think I have anything to add, these are all good suggestions to move forward

**Comment by luhring** [comment]
Awesome! @alfredodeza @wagoodman What's the action associated with this ticket? Are we changing a bunch of code and then that PR closes this ticket? Or was this ticket more trying to achieve a forward-looking philosophical alignment, with incremental changes for the better?

**Comment by spiffcs** [comment]
Closing this issue as stale for now - a lot has changed in two years and our datashape and checks against nil/null values in internal code and external json has improved a lot. We also follow @wagoodman's recommendations consistently when adding new code to the project. If other users find fault with fields or the shape we will address those on separate community filed issues.
