### ISSUE TITLE
Ability to ignore vulnerability matches (to help manage false positives)

### ISSUE THREAD

**Issue by cdhaydensmith** [anchore/grype#198]
**What would you like to be added**:
I would like to be able to quickly add false positives or accepted vulnerabilities/CVE's to a list so that they are not returned by Grype
**Why is this needed**:
This creates less noise for devs and security teams that may want to ignore any false positives or accepted vulnerabilities presented by grype and solely focus on relevant vulns
**Additional context**:

**Comment by w3dev-dk** [comment]
I have only been using this for a short while and I already loves it. But this feature is crucial.

For eksempel: The python package management system `pip` has a vulnerability CVE-2018-20225 - The community has accepted this vulnerability but as a feature and instead of "fixing" it they have added disclaimers about the issue in the documentation. The vulnerability is only present if using the tool in a certain way, which we don't, so it would be nice to be able to "whitelist" CVE-2018-20225 to make the tool useful in our CI pipeline - else we will just get false positives.

I'm not that experienced go developer but if you lag resources and could point me in the right direction then I could try and create a PR for you @wagoodman ?

**Comment by nicolai92** [comment]
Hi,

I also rely on the whitelist functionality in my current project, that's why I built it on my own using bash, as long as the official one is not yet released.

It basically uses a `whitelist.txt` file, where each entry contains a security issue (CVE, GHSA), filters the output of `grype` and counts the remaining lines, that contain `Critical` or `High`.

```
grype python:3.9.6-slim -q | tail -n +2 | grep -v -F -f whitelist.txt | tee out.txt
cat out.txt
export COUNT=$(grep 'High\|Critical' out.txt | wc -l | xargs)

if [ $COUNT -gt 0 ]; then
    unset COUNT
    rm out.txt
    exit 1
fi

unset COUNT
rm out.txt
```

**Comment by luhring** [comment]
I think this feature makes sense. No vulnerability matcher will ever be 100% perfect, so it'd be great to have a way to make the workflow as painless as possible for users. 😃 

Some thoughts:

1. **The term "allow list" should be preferred over the term "whitelist".**
2. We should think through if this really is an "allow list" in the first place. Maybe it is... but Grype isn't really a gating mechanism, although _it is_ when using the `--fail-on` flag. It seems like the expected functionality is that a specified set of vulnerability matches are _omitted_ from the result list, whether or not `--fail-on` is being used. This seems more like a "hide list", "omit list", etc. If there's a gating mechanism being applied to a workflow downstream of Grype, that would seem like a more appropriate place to find an "allow list", not in Grype itself.
3. Any output from Grype should **state explicitly that it is omitting some results** due to a specific user configuration. This is crucial for transparency and feedback. If a user accidentally omits a legitimate match, there should be some indication that one or more matches that Grype found are being withheld from the user, which gives the user an opportunity to uncover the hidden results.
4. What kind of entries should appear in the user-supplied list? Just vulnerability identifiers? Or vulnerabilities paired with packages? Is it possible that we'd want to omit a vulnerability match that was wrongly surfaced for package A, but should in fact be surfaced for package B?

**Comment by luhring** [comment]
cc: @wagoodman

**Comment by mirekphd** [comment]
Sorry guys / gals, but lack of false positives whitelisting is a major blocker in practical applications (i.e. in CI/CD pipelines). It would prevent our users from ordering Jenkins builds of fresh images... which is required for on-demand self-service packages installation (sometimes for weeks).

But I'm surprised at how long this takes to implement here. A one-man project `clair-scanner` has had whitelists for a long time... at least since 2017 (see https://github.com/arminc/clair-scanner/issues/31). It's a hardly new concept that requires long deliberation. Sorry, but adding this missing functionality should have a HIGH priority in my opinion (it certainly prevented our organization from adopting Anchore or Grype).

**Comment by wagoodman** [comment]
Hey, folks! I also agree that integrating an allow list is a must-have in grype, since ultimately the purpose is to integrate grype into workflows, not only be a stand alone tool to show what vulnerabilities are present.

I want to respond and extend on https://github.com/anchore/grype/issues/198#issuecomment-924484250 :

regarding 3: I agree regarding whatever matches on the list of exceptions should still be visible somewhere, preferably in the grype JSON format (in a separate new section outside of the `matches` key), which is representative of the internal model within grype. In other formats such as the table output or CycloneDX it makes sense to omit these elements entirely.

regarding 1 & 2: Given some of the other points about omitting/allowing/hiding , `ignore` is probably a better word choice here. We want it to be visible in some aspects (in the JSON output) but hidden in others, but overall not considered at all in gating (with `--fail-on`).

regarding 4: Match selection from items in the ignore list could go many different ways. However this ignore list is expressed it would be ideal to allow for extensibility without having to implement several selection approaches up front. My guess is if we go with the simplest approach first (e.g. a simple CVE list) that we'd wind up needing to immediately come back and extend it --however, the solution should probably support at least this case. 

## thoughts on users

After a little bit of thought, I think these are the common use cases / users:

1. Users crafting a long-lived ignore list in a single repo that is tailored for scanning a **single container image** in CI.
2. Users crafting a long-lived ignore list that's meant for **all of my images** that I scan in CI.
3. Users supplying exceptions in an **ad-hoc fashion** for exploratory reasons.

## thoughts on format

Vulnerability-package pairing is common as well, however, do we pair on the package name? In java packages it is common to have multiple of the same jars present with slightly different versions and build sources. Does that imply we allow for vulnid+packagename+version pairing? Maybe vulnid+packagename+version+type+location? I'm not certain. But I think the format we choose should allow for extension of these kinds of pairings to be added later without having to swap over to an entirely different format. 

As a side note, I also think whatever is selected should attempt to avoid expressing categorical exceptions based on the quality of the vulnerability (e.g. "ignore anything with a severity of 'low'" or "ignore anything with CVSS score > 8.0"). I have a similar opinion when it comes to package selection; we should allow for expressions such as "ignore all packages except for X@version". Overall this ignore list is intended to "fix" exceptions for the purpose of correctness, not cull results to favor downstream quality gating.

Here are some configuration examples to get the conversation started:

_ignore by a simple list of CVEs_: "ignore any matches that have X,Y,Z vulnerability IDs"
```yaml
ignore:
- CVE-2019-25013
- CVE-2017-11164
- CVE-2018-22465
```

_ignore by basic package information_: "ignore any matches from the packages X and Y@version"
```yaml
ignore:
- package: libc
- package:
     name: libpcre3
     version: 2:8.39-12build1
```

_ignore by vulnerability + package information_: "ignore matches for vulnerability X only for package Y@version"
```yaml
ignore:
- package: libc
   vulnerability: CVE-2016-10228
- package:
     name: libpcre3
     version: 2:8.39-12build1
  vulnerability: CVE-2019-20838
```

_ignore by package location information_: "ignore matches for any packages from /some/location in the scan target"
```yaml
ignore:
- package:
     location: /usr/local/lib/python3.6/site-packages/**/*
```

These above examples are not meant to be mutually exclusive:
```yaml
ignore:
- CVE-2019-25013
- package: libc
- vulnerability: CVE-2019-20838
   package:
     name: libpcre3
     version: 2:8.39-12build1
- package:
     location: /usr/local/lib/python3.6/site-packages/**/*
```

What package and vulnerability fields should we start with? My suggestion is only fields that are in the above example: `package.name`, `package.version`, `package.location`, and `vulnerability`. We can always extend to more fields in the future.

## thoughts on input

Users 1 & 2 imply a config file that can be checked in where as user 3 really is looking for something on the CLI as to prevent needing to continually change a config file. This somewhat hints that the expressibility of these ignored items from the CLI probably doesn't need to be as in-depth/detailed/flexible as a config file.

With these observations, I think we can sketch out some rough CLI options (as a starter for a conversation here, **_not_** a finalized suggestion):

```
syft --ignore CVE-2016-10228
syft --ignore-package libpcre3
syft --ignore-package libpcre3@2:8.39-12build1 --ignore-package libpcre3
syft --ignore-package libpcre3,libc6,libpcre3@2:8.39-12build1
syft --ignore-location '/usr/local/lib/python3.6/site-packages/**/*'
```

Note that the above examples don't allow for combining concepts, such as "ignore vuln X for package Y@version". My assumption is that if you need this kind of detail then a config file is a better place to express it.

Looking toward Users 1 & 2, you can either depend on the existing application configuration, adding a new `ignore:` section, or additionally allow for specifying a separate config:
```
syft --ignore-config ./some.yaml
```

I think both are good options (and are not mutually exclusive!).

## questions I have

1. I think I have at least one major question left given the above examples: do we want to allow for selection of these ignore lists by images or container repos? I feel that User 2 would want the ability to have a single ignore file where they could specify exceptions that should apply to all images uniformly and some exceptions that should only apply to a subset of images (e.g. "these exceptions apply only to `org/my-image` and these other exceptions only apply to `org/some-other-image`")

**Comment by luhring** [comment]
@wagoodman Makes a lot of sense!

>"ignore" is probably a better word choice here

Agreed.

> thoughts on format [...]

I think this approach makes sense. I think the ideal is to provide enough support for the bare minimum needs, while still allowing for iteration as we discover new concrete needs.

>I think I have at least one major question left given the above examples: do we want to allow for selection of these ignore lists by images or container repos? [...]

To that end, my suggestion would be not to handle image/repo-level configuration in the first pass. I can understand the hypothetical use case, but I think this starts to add more complexity to the interface with users, and it'd be nice to prove that it's warranted first. Just my two cents.

**Comment by luhring** [comment]
Synced up with @wagoodman on an initial approach. I'll detail the latest thinking here.

First off, here's what it means to be "ignored":

- internally to Grype's business logic, the term "ignored" can apply only to `matches` (i.e. not packages or vulnerabilities)
- if a match is "ignored":
    - it is not considered during the `--fail-on` gating
    - it does not appear in any of Grype's output formats, except `json` (Grype's own lossless format) and `template` (see fuller explanation below in the "Output" section)

### Configuration

Define a new `IgnoreRule` data structure that would be used to define criteria which, if applicable to a `Match`, causes the match to be ignored. Example of this data structure:

```go
type IgnoreRule struct {
    Vulnerability string
    Package IgnoreRulePackage
}

type IgnoreRulePackage struct {
    Name string
    Version string
    Location string
}
```

#### Configuration Input

For this first pass, we'll focus on use cases that involve specifying "ignore rules" via the application's existing **configuration file**. We won't add any CLI args. If environment variable config works naturally given our existing architecture, that's great, but we won't worry about ensuring support for now.

In general, users specify a list of ignore rules, where each item in the list looks like this:

```yaml
- vulnerability: CVE-2019-20838
  package:
    name: libpcre3
    version: 2:8.39-12build1
    location: "/usr/local/lib/python3.6/site-packages/**/*"
```

Users don't need to fill out all possible fields. For example, they can specify only a package name:

```yaml
- package:
    name: libpcre3
```

... or just a vulnerability ID:

```yaml
- vulnerability: CVE-2019-20838
```

As a convenience, we'll also support a simplified format for identifying matches by vulnerability ID:

```yaml
- CVE-2019-20838
```

### Output

As mentioned above, in general, all Grype outputs completely exclude all matches for which there are applicable ignore rules.

The exceptions to this are the view models that drive the `json` and `template` output options. For these options, matches that have been "ignored" are moved to a _separated off collection_ and do not appear in the existing "matches" collection in the output. This is so that consumers of Grype's output can count on the "matches" collection not to have matches that should be ignored.

This separated off collection collection (something like "ignoredMatches") will appear as a sibling to "matches" and contain only the ignored matches. Each object item in the list of "ignoredMatches" will have the same data structure as that of the "matches" list, except that each "match" object will have an additional property, called something like "applicableIgnoreRules". This property is an array of objects, where each object corresopnds to the `IgnoreRule` struct described above. **All** rules (not just the **first** rule) that apply to a given match will be included in the "applicableIgnoreRules" array. The purpose of this additional property is to provide visibility to consumers as to why a given match has been ignored, pointing back to one or more ignore rules specified by the user.

**Comment by luhring** [comment]
### A consideration for the future...

(This is explicitly **_not in scope_** for the first release of this functionality.)

We need to consider the potential effect this new "ignore" functionality will have on the feedback loop we have with users for learning about false positives. From the perspective of Grype maintainers, the "worst case scenario" is that we never hear about false positives again, despite the fact that Grype is still producing a lot of false positives — which means that new Grype users always need to figure out our "ignore rules" functionality. Notwithstanding the case for providing the "ignore" functionality in the first place, we should consider options for helping users to let us know about false positives that are occuring, even if their immediate pain is solved by ignore rules.

Some initial ideas...

1. Introduce a subcommand in `grype` that opens a browser tab to a "false positive report" (new issue template) in Grype on GitHub.
2. Have the command write some text to stderr that can be copied verbatim to the issue that expresses what false positives are being ignored.
3. When the user is invoking the ignore functionality, provide a web link (via a line of text written to stderr) asking for the false positives to be reported to the Grype maintainers. (This could get annoying very quickly, and if implemented, should be able to be silenced via configuration.)

**Comment by luhring** [comment]
I'll start looking at this! 🏃

**Comment by luhring** [comment]
### Change in design — "vulnerability" in rules

We've decided that we won't yet add support for the "bare vulnerability" `- CVE-1234-56789` syntax in the app config just yet. This would require custom unmarshaling for the Viper config, and then we'd need to ensure support for all of the config formats that Viper supports.

For now, in order to ignore a particular vulnerability by ID, users will specify `- vulnerability: CVE-1234-56789`.
