### ISSUE TITLE
Error when omitting Docker image tag for images with multiple local tags

### ISSUE THREAD

**Issue by Overcolor** [anchore/grype#215]
**What happened**:
While I was trying to analyze anchore/inline-scan:latest (Image ID: 12a7b00e9cc7 ) grype gave me this Error:

`[0233] ERROR failed to catalog: could not fetch image 'anchore/inline-scan': tarball must contain only a single image to be used with tarball.Image`

**What you expected to happen**:
To analyze the Image without Errors.

**How to reproduce it (as minimally and precisely as possible)**:
`grype anchore/inline-scan:latest`

**Anything else we need to know?**:
I also run it with syft 0.7.1 and 0.8.0. But there doesn't seem to be a problem.

**Environment**:
- Output of `grype version`:
Application:          grype
Version:              0.5.0
BuildDate:            2020-11-20T13:15:35Z
GitCommit:            b03cd13e76df840bdd01d0ef56dbcfc95513796f
GitTreeState:         clean
Platform:             linux/amd64
GoVersion:            go1.14.12
Compiler:             gc
Supported DB Schema:  1

- OS (e.g: `cat /etc/os-release` or similar):
NAME="Ubuntu"
VERSION="20.04.1 LTS (Focal Fossa)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 20.04.1 LTS"
VERSION_ID="20.04"

**Comment by luhring** [comment]
Hi @Overcolor, thanks for the report! I'm not able to reproduce that error when I use the command you included (`grype anchore/inline-scan:latest`). I've tried on Ubuntu and macOS.

That being said, I was able to reproduce that error if I change the command to `grype anchore/inline-scan` — i.e. with no tag specified. This is because when grype makes the request to Docker, Docker finds multiple tags (e.g. `latest` and `v0.7.0`), and sends back multiple images. However, I think we should consider a better way to handle this, for example by defaulting to a `latest` tag if multiple tags are present like some other tools do. This warrants more discussion internally.

Would you mind trying the command again, both with and without the tag specified, and let me know if you see what I'm seeing?

**Comment by Overcolor** [comment]
Hey :) @luhring 
You are right, i was using the same command like you, but did assume, that only the latest was pulled. 
I did remove the old images and could not recreate the issue, most likely because the image was updated.

**Comment by luhring** [comment]
Okay, thanks for letting me know! Glad to hear the pain is gone for the moment.

We're going to think on this to figure out the "right way" to handle multiple image tags for the user's input.

**Comment by wagoodman** [comment]
from an offline conversation, we could also canonicalize the user input and expand out a default tag of "latest" in theses cases.

**Comment by tgerla** [comment]
I believe this is fixed thanks to anchore/syft#411.
