### ISSUE TITLE
Add support for gradle in Java

### ISSUE THREAD

**Issue by jinsihou19** [anchore/grype#2236]
What would you like to be added:

Add support for gradle in Java.

Why is this needed:

Gradle project is one of the most popular Java projects.

**Comment by willmurphyscode** [comment]
Hi @jinsihou19! Thanks for opening an issue.

I don't have enough information to understand your request yet. There are a few ways we _already_ support Gradle, and I'm not sure whether this answers your use case or not.

In order to "support" a given package ecosystem or build tool or whatever, two things need to happen: Grype needs to find the packages, and Grype needs to have a vulnerability data source for the packages. Generally, Grype invokes Syft internally to find packages, but you can also give Grype your own SBOM.

1. We have vulnerabilities in the database for Java packages via GitHub security advisories (GHSA), which covers Maven Central, so if Grype knows about a Java package, it can look and see if there are vulnerabilities against it. So if Grype is given an SBOM with Java packages in it, or finds Java packages itself, Grype can search for vulnerabilities that affect the packages.
2. We already find Java packages a few different ways: we parse Gradle _lockfiles_ in Syft, and we catalog JARs themselves in Syft.

So when I say we support Gradle, what I mean is: if there are JARs (or, in a directory scan, gradle lockfiles), Grype will find Java packages from them, and will look for vulnerabilities in them from GHSA.

There are a couple of limitations here:
1. When scanning images, we don't consider gradle lockfiles. (This is because we assume that, in building the image, Gradle would have downloaded the actual JARs for the dependencies, and we will get better information by looking at those.)
2. When scanning directories, we also consider Grade _lockfiles_, but not Grade scripts like build.gradle or build.gradle.kts, because the Gradle scripts in Kotlin or Groovy are little programs, and we have no way to know what they'd do without running them. (See anchore/syft#2472). The upshot here is that you need to tell Gradle to install everything and generate a lockfile before a Syft or Grype directory scan will get you accurate information.

Does this answer your question? Are you doing a scan that didn't find a vulnerability you expected to? Are you trying to scan images or directories? Until we know more about your use case, we can only make general answers.

**Comment by jinsihou19** [comment]
> Hi @jinsihou19! Thanks for opening an issue.你好！感谢您打开问题。
> 
> I don't have enough information to understand your request yet. There are a few ways we _already_ support Gradle, and I'm not sure whether this answers your use case or not.我还没有足够的信息来理解您的请求。_我们已经_通过多种方式支持 Gradle，我不确定这是否能满足您的用例。
> 
> In order to "support" a given package ecosystem or build tool or whatever, two things need to happen: Grype needs to find the packages, and Grype needs to have a vulnerability data source for the packages. Generally, Grype invokes Syft internally to find packages, but you can also give Grype your own SBOM.为了 “支持” 给定的包生态系统或构建工具或其他任何东西，需要做两件事：Grype 需要找到包，而 Grype 需要拥有包的漏洞数据源。通常，Grype 在内部调用 Syft 来查找包，但你也可以给 Grype 你自己的 SBOM。
> 
> 1. We have vulnerabilities in the database for Java packages via GitHub security advisories (GHSA), which covers Maven Central, so if Grype knows about a Java package, it can look and see if there are vulnerabilities against it. So if Grype is given an SBOM with Java packages in it, or finds Java packages itself, Grype can search for vulnerabilities that affect the packages.通过 GitHub 安全公告 （GHSA） 在 Java 包的数据库中存在漏洞，该公告涵盖 Maven Central，因此，如果 Grype 知道某个 Java 包，它可以查看是否存在针对它的漏洞。因此，如果 Grype 获得包含 Java 包的 SBOM，或者找到 Java 包本身，Grype 可以搜索影响包的漏洞。
> 2. We already find Java packages a few different ways: we parse Gradle _lockfiles_ in Syft, and we catalog JARs themselves in Syft.我们已经通过几种不同的方式找到了 Java 包：在 Syft 中解析 Gradle _锁文件_，并在 Syft 中对 JAR 本身进行编目。
> 
> So when I say we support Gradle, what I mean is: if there are JARs (or, in a directory scan, gradle lockfiles), Grype will find Java packages from them, and will look for vulnerabilities in them from GHSA.因此，当我说我们支持 Gradle 时，我的意思是：如果有 JAR（或者，在目录扫描中，gradle lockfiles），Grype 将从中找到 Java 包，并从 GHSA 中查找其中的漏洞。
> 
> There are a couple of limitations here:这里有几个限制：
> 
> 1. When scanning images, we don't consider gradle lockfiles. (This is because we assume that, in building the image, Gradle would have downloaded the actual JARs for the dependencies, and we will get better information by looking at those.)扫描图片时，我们不会考虑 gradle lockfile。（这是因为我们假设，在构建映像时，Gradle 会下载依赖项的实际 JAR，我们将通过查看这些 JAR 来获得更好的信息。
> 2. When scanning directories, we also consider Grade _lockfiles_, but not Grade scripts like build.gradle or build.gradle.kts, because the Gradle scripts in Kotlin or Groovy are little programs, and we have no way to know what they'd do without running them. (See [Gradle support (non-lockfiles) syft#2472](https://github.com/anchore/syft/issues/2472)). The upshot here is that you need to tell Gradle to install everything and generate a lockfile before a Syft or Grype directory scan will get you accurate information.在扫描目录时，我们还会考虑 Grade _lockfiles_，而不是 build.gradle 或 build.gradle.kts 等 Grade 脚本，因为 Kotlin 或 Groovy 中的 Gradle 脚本都是小程序，如果不运行它们，我们无法知道它们会做什么。（见  [Gradle support (non-lockfiles) syft#2472](https://github.com/anchore/syft/issues/2472) ）。这里的结果是，您需要告诉 Gradle 安装所有内容并生成一个锁定文件，然后 Syft 或 Grype 目录扫描才能为您提供准确的信息。
> 
> Does this answer your question? Are you doing a scan that didn't find a vulnerability you expected to? Are you trying to scan images or directories? Until we know more about your use case, we can only make general answers.这回答了您的问题吗？您是否正在进行的扫描没有找到您预期的漏洞？您是否正在尝试扫描图像或目录？在我们进一步了解您的使用案例之前，我们只能做出一般性的回答。

Thank you for your answer, I will try the solution you mentioned. If I have any questions later, I will reply.

> Hi @jinsihou19! Thanks for opening an issue.
> 
> I don't have enough information to understand your request yet. There are a few ways we _already_ support Gradle, and I'm not sure whether this answers your use case or not.
> 
> In order to "support" a given package ecosystem or build tool or whatever, two things need to happen: Grype needs to find the packages, and Grype needs to have a vulnerability data source for the packages. Generally, Grype invokes Syft internally to find packages, but you can also give Grype your own SBOM.
> 
> 1. We have vulnerabilities in the database for Java packages via GitHub security advisories (GHSA), which covers Maven Central, so if Grype knows about a Java package, it can look and see if there are vulnerabilities against it. So if Grype is given an SBOM with Java packages in it, or finds Java packages itself, Grype can search for vulnerabilities that affect the packages.
> 2. We already find Java packages a few different ways: we parse Gradle _lockfiles_ in Syft, and we catalog JARs themselves in Syft.
> 
> So when I say we support Gradle, what I mean is: if there are JARs (or, in a directory scan, gradle lockfiles), Grype will find Java packages from them, and will look for vulnerabilities in them from GHSA.
> 
> There are a couple of limitations here:
> 
> 1. When scanning images, we don't consider gradle lockfiles. (This is because we assume that, in building the image, Gradle would have downloaded the actual JARs for the dependencies, and we will get better information by looking at those.)
> 2. When scanning directories, we also consider Grade _lockfiles_, but not Grade scripts like build.gradle or build.gradle.kts, because the Gradle scripts in Kotlin or Groovy are little programs, and we have no way to know what they'd do without running them. (See [Gradle support (non-lockfiles) syft#2472](https://github.com/anchore/syft/issues/2472)). The upshot here is that you need to tell Gradle to install everything and generate a lockfile before a Syft or Grype directory scan will get you accurate information.
> 
> Does this answer your question? Are you doing a scan that didn't find a vulnerability you expected to? Are you trying to scan images or directories? Until we know more about your use case, we can only make general answers.

Thank you for your answer, I will try the solution you mentioned. I will reply if I have any questions later.

**Comment by jinsihou19** [comment]
> Hi @jinsihou19! Thanks for opening an issue.
> 
> I don't have enough information to understand your request yet. There are a few ways we _already_ support Gradle, and I'm not sure whether this answers your use case or not.
> 
> In order to "support" a given package ecosystem or build tool or whatever, two things need to happen: Grype needs to find the packages, and Grype needs to have a vulnerability data source for the packages. Generally, Grype invokes Syft internally to find packages, but you can also give Grype your own SBOM.
> 
> 1. We have vulnerabilities in the database for Java packages via GitHub security advisories (GHSA), which covers Maven Central, so if Grype knows about a Java package, it can look and see if there are vulnerabilities against it. So if Grype is given an SBOM with Java packages in it, or finds Java packages itself, Grype can search for vulnerabilities that affect the packages.
> 2. We already find Java packages a few different ways: we parse Gradle _lockfiles_ in Syft, and we catalog JARs themselves in Syft.
> 
> So when I say we support Gradle, what I mean is: if there are JARs (or, in a directory scan, gradle lockfiles), Grype will find Java packages from them, and will look for vulnerabilities in them from GHSA.
> 
> There are a couple of limitations here:
> 
> 1. When scanning images, we don't consider gradle lockfiles. (This is because we assume that, in building the image, Gradle would have downloaded the actual JARs for the dependencies, and we will get better information by looking at those.)
> 2. When scanning directories, we also consider Grade _lockfiles_, but not Grade scripts like build.gradle or build.gradle.kts, because the Gradle scripts in Kotlin or Groovy are little programs, and we have no way to know what they'd do without running them. (See [Gradle support (non-lockfiles) syft#2472](https://github.com/anchore/syft/issues/2472)). The upshot here is that you need to tell Gradle to install everything and generate a lockfile before a Syft or Grype directory scan will get you accurate information.
> 
> Does this answer your question? Are you doing a scan that didn't find a vulnerability you expected to? Are you trying to scan images or directories? Until we know more about your use case, we can only make general answers.

Thank you for your answer, I will try the solution you mentioned.  I will reply if I have any questions later.
