### ISSUE TITLE
Vulnerability check should be more "greedy"

### ISSUE THREAD

**Issue by stephan-klein** [anchore/grype#252]
**What happened**:
Im scanning a directory including a jar file called [picketlink-fed-1.0.4.final.jar](https://repository.jboss.org/nexus/content/repositories/releases/org/picketlink/picketlink-fed/1.0.4.final/)

It contains following vulnerability:
https://nvd.nist.gov/vuln/detail/CVE-2015-6254

Grype does not find the vulnerability

**What you expected to happen**:
Im expecting Grype to find this vulnerability

**How to reproduce it (as minimally and precisely as possible)**:
Put jar file into current dir
```
[root@paratlvapp03 libs]# grype dir:.
 ✔ Vulnerability DB     [no update available]
New version of grype is available: 0.8.0
 ✔ Cataloged image      [1 packages]
 ✔ Scanned image        [0 vulnerabilities]
No vulnerabilities found
```

When i change the name of the jar file the scanner finds it:
```
[root@paratlvapp03 libs]# mv picketlink-fed-1.0.4.final.jar picketlink-1.0.4.final.jar
[root@paratlvapp03 libs]# grype .
 ✔ Vulnerability DB     [no update available]
 ✔ Cataloged image      [1 packages]
 ✔ Scanned image        [3 vulnerabilities]
NAME        INSTALLED    FIXED-IN  VULNERABILITY  SEVERITY
picketlink  1.0.4.final            CVE-2015-0277  Medium
picketlink  1.0.4.final            CVE-2015-3158  Medium
picketlink  1.0.4.final            CVE-2015-6254  Medium
```

**Environment**:
- Output of `grype version`:

```
Application:          grype
Version:              0.8.0
BuildDate:            2021-03-17T18:52:17Z
GitCommit:            ec1f11ffcd262f04e849248c84c57bd80ca44ac9
GitTreeState:         clean
Platform:             linux/amd64
GoVersion:            go1.14.15
Compiler:             gc
Supported DB Schema:  1
```

- OS (e.g: `cat /etc/os-release` or similar):
```
NAME="CentOS Linux"
VERSION="7 (Core)"
ID="centos"
ID_LIKE="rhel fedora"
VERSION_ID="7"
PRETTY_NAME="CentOS Linux 7 (Core)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:centos:centos:7"
HOME_URL="https://www.centos.org/"
BUG_REPORT_URL="https://bugs.centos.org/"

CENTOS_MANTISBT_PROJECT="CentOS-7"
CENTOS_MANTISBT_PROJECT_VERSION="7"
REDHAT_SUPPORT_PRODUCT="centos"
REDHAT_SUPPORT_PRODUCT_VERSION="7"
```

**Comment by luhring** [comment]
Hi @stephan-klein, thanks for the issue! I'm not very experienced with Java, so I'll need your help following along here.

First, it sounds like by "be more greedy", you're saying you expect Grype to match a given package to vulnerabilities where the package name is not quite the same, but is "similar" in some way — e.g. here we find the package `picketlink-fed`, and the vulnerability appears to describe the package `picketlink`.

My next question is this: How could we verify that https://nvd.nist.gov/vuln/detail/CVE-2015-6254 **_should be_** matched with [picketlink-fed-1.0.4.final.jar](https://repository.jboss.org/nexus/content/repositories/releases/org/picketlink/picketlink-fed/1.0.4.final/picketlink-fed-1.0.4.final.jar)?

When I look at the NVD page, I don't see any mention of "fed". And when I browse around the artifacts at https://repository.jboss.org/nexus/content/repositories/releases/org/picketlink/picketlink-fed/1.0.4.final/, I see an apparent distinction made between https://repository.jboss.org/nexus/content/repositories/releases/org/picketlink/picketlink-fed/ and https://repository.jboss.org/nexus/content/repositories/releases/org/picketlink/picketlink/. What's the relationship here? Are we saying `picketlink-fed` includes the code or artifacts of `picketlink`, and that's why `picketlink-fed` has the same vulnerabilities of `picketlink`?

Thanks for helping me follow along!

**Comment by stephan-klein** [comment]
Checking your answer i have to agree that the scanner works properly. I have no evidence that the Vulnerability affects also picketlink-fed. Thanks for taking the time to respond.

**Comment by luhring** [comment]
Sure thing! Let us know if you want to revisit at some point.
