### ISSUE TITLE
Cannot handle Syft SBOM for directory scans

### ISSUE THREAD

**Issue by luhring** [anchore/grype#298]
**What happened**:
Grype wasn't able to handle input of a Syft SBOM JSON document, when the Syft scan was of a _directory_ (as opposed to an image).

**What you expected to happen**:
Grype should be able to process directory SBOMs just as well as image SBOMs.

**How to reproduce it (as minimally and precisely as possible)**:

```shell
# Create the SBOM
syft -o json dir:./some/directory > ./dir.syft.json

# Reproduce via STDIN
cat ./dir.syft.json | grype
# [0000] ERROR failed to catalog: unable to process input for scanning: ''

# Reproduce via SBOM scheme
grype sbom:./dir.syft.json
# [0000] ERROR failed to catalog: unable to process input for scanning: 'sbom:./dir.syft.json'
```

**Anything else we need to know?**:

This seems to be reproducible with any recent version of Syft, and with Grype as of v0.8.0. Image scans seem unaffected by this.

**Environment**:
- Output of `grype version`:
```
Application:          grype
Version:              0.10.2
BuildDate:            2021-04-14T22:19:15Z
GitCommit:            48f12f7b7aac0ff5c3d30a790d23088281aa3aef
GitTreeState:         clean
Platform:             darwin/amd64
GoVersion:            go1.16.3
Compiler:             gc
Supported DB Schema:  2
```
- OS (e.g: `cat /etc/os-release` or similar):
macOS 11.2.3 (20D91)

**Comment by Karreg** [comment]
I second that issue. I'm trying to figure out if grype can replace dependency check, and it fails at the same step.

**Comment by jeff-cook** [comment]
Also happening for the following versions.

```
$ grype version
Application:          grype
Version:              0.15.0
BuildDate:            2021-07-14T15:37:24Z
GitCommit:            283bd3be5f586c9651b38089460f327db4860e45
GitTreeState:         clean
Platform:             darwin/amd64
GoVersion:            go1.16.5
Compiler:             gc
Supported DB Schema:  3
```

```
$ syft version
Application:   syft
Version:       0.19.1
BuildDate:     2021-06-30T17:32:06Z
GitCommit:     fee35dd1753308fc887da744de5d0c66947c7493
GitTreeState:  clean
Platform:      darwin/amd64
GoVersion:     go1.16.5
Compiler:      gc
```

**Comment by dakaneye** [comment]
@luhring @wagoodman I think I've found the root cause of this issue.

When syft catalogs a directory for packages, it outputs the `source` of the sbom like so: 
```
 "source": {
  "type": "directory",
  "target": "./<whatever directory was passed>"
 }
```
You should be able to find this block in your own generated SBOM json file near the bottom.

Then, when grype is unpacking direct sbom output in the `pkg.syft_json_provider.parseSyftJSON` method, it is doing some custom JSON unmarshalling in `syftSource.UnmarshalJSON`. It looks like that method only supports the `image` type at present.

This seems to be a pretty straightforward solution:
* Right now, the `syftSource` target is of type `interface{}`, [which _should_ be possible to map from a string](https://yourbasic.org/golang/interface-to-string/). The unpacker is using the json.RawMessage type, [which is just a byte array](https://stackoverflow.com/questions/40632802/how-to-convert-byte-array-to-string-in-go)
* Add a new block to the custom unmarshal method to support `directory` type

Example:
```
	case "directory":
		s.Target = string(unpacker.Target[:])
```

**Comment by wagoodman** [comment]
@dakaneye agreed! Did you want to take a stab at the implementation for this?

**Comment by TheDiveO** [comment]
ping: any e.t.a.?

**Comment by dakaneye** [comment]
Sorry all, missed this notification. I will be able to take a look this week, hopefully get a PR open soon!

**Comment by dakaneye** [comment]
@wagoodman I applied the fix above and ran it manually as @luhring did above, but only using the SBOM scheme did it work. When piped in, I'm seeing the following:
```
Error: 1 error occurred:
	* failed to catalog: unable to process input for scanning: ''


^[[2;1R^[[1;1RUsage:
  grype [IMAGE] [flags]
  grype [command]

Available Commands:
  completion  Generate a shell completion for Grype (listing local docker images)
  db          vulnerability database operations
  help        Help about any command
  version     show the version

Flags:
  -c, --config string     application config file
  -f, --fail-on string    set the return code to 1 if a vulnerability is found with a severity >= the given severity, options=[negligible low medium high critical]
  -h, --help              help for grype
  -o, --output string     report output formatter, formats=[json table cyclonedx template]
  -q, --quiet             suppress all logging output
  -s, --scope string      selection of layers to analyze, options=[Squashed AllLayers] (default "Squashed")
  -t, --template string   specify the path to a Go template file (requires 'template' output to be selected)
  -v, --verbose count     increase verbosity (-v = info, -vv = debug)

Use "grype [command] --help" for more information about a command.

1 error occurred:
	* failed to catalog: unable to process input for scanning: ''


~/dev/repos/grype issue-298-directory-sbom !1 ?1 > 1RR
```

I suspect this is probably part of another issue though, perhaps related to https://github.com/anchore/grype/issues/267.

For now, maybe we can get this fix in because it works with the SBOM scheme, and think about the other bit in a separate issue?
