### ISSUE TITLE
Mismatched EL release versions causing false positive

### ISSUE THREAD

**Issue by emosbaugh** [anchore/grype#316]
**What happened**:

I am seeing what looks to be a false positive. I gather this is related to issue https://github.com/anchore/syft/issues/408. 

```
libldb                       1.5.4-2.el7            0:1.5.4-2.el7_9     CVE-2021-20277       High      
```

**What you expected to happen**:

No vulnerability should be reported

**How to reproduce it (as minimally and precisely as possible)**:

```
$ cat Dockerfile
FROM centos:7

RUN yum install -y libldb
$ docker build -t libldb-vuln .
$ grype libldb-vuln:latest | grep libldb
libldb                       1.5.4-2.el7            0:1.5.4-2.el7_9          CVE-2021-20277    High
```

**Anything else we need to know?**:

**Environment**:

```
$ grype version
Application:          grype
Version:              0.11.0
BuildDate:            2021-04-22T21:51:14Z
GitCommit:            0a46e54aae837135f73d2ff18a84061189ee6f28
GitTreeState:         clean
Platform:             linux/amd64
GoVersion:            go1.16.3
Compiler:             gc
Supported DB Schema:  2
```

```
$ docker run ... cat /etc/centos-release
CentOS Linux release 7.9.2009 (Core)
```

**Comment by wagoodman** [comment]
It seems that this isn't entirely an epoch comparison problem, see the following:
- https://lists.centos.org/pipermail/centos-announce/2021-April/048299.html
- https://access.redhat.com/errata/RHSA-2021:1072

Note that the updated package for redhat is:
```
libldb-1.5.4-2.el7_9.x86_64.rpm
```
However, the updated package for centos is:
```
libldb-1.5.4-2.el7.x86_64.rpm
```
Take note of the release of `el7` vs `el7_9`.

This mainly has to do with the fact that we use the RHEL feeds for Centos vulnerabilities --very close, but at times there are differences.

**Comment by wagoodman** [comment]
@emosbaugh there isn't an ideal way to fix this. I'll be putting in enhancements shortly for the epoch enhancement, however, **this particular false positive will continue to occur** due to the mismatching release versions noted above. 

I'm not entirely certain if this is an oversight on CentOS's part, if there is precedence for this in their release process for this mutation in the release (since this is seen in CentOS 7.9, I don't see why that would be the case), or if this has something to do with [CentOS Stream](https://blog.centos.org/2020/12/centos-stream-is-continuous-delivery/) (but I don't see why since I don't think that should affect CentOS 7?).

I'm going to leave this issue open since the bad behavior still exists, but wanted to let you know that there isn't a clear path forward on this particular problem for this specific package. 

On a more general note, finding more cases like these may influence the urgency for features like  https://github.com/anchore/grype/issues/198 for handling "persistent false positives" like this.

**Comment by luhring** [comment]
Based on the investigation above, we'll close with `wontfix` for the time being. If anyone discovers new information that points to a viable solution we can implement, just add a comment here! Thanks.
