### ISSUE TITLE
Scanning root folder makes grype running forever

### ISSUE THREAD

**Issue by Karreg** [anchore/grype#326]
**What happened**:

When using this command from within an container to scan, grype will loop on catalog scanning:

`grype dir:/`

![image](https://user-images.githubusercontent.com/9166144/119665868-19c7ca00-be35-11eb-809d-ac38ed4b7ee6.png)

**What you expected to happen**:

The scan should be executed

**How to reproduce it (as minimally and precisely as possible)**:

* `docker run -it debian:9 /bin/bash`
* `apt-get update && apt-get install curl`
* `curl -sSfL https://raw.githubusercontent.com/anchore/grype/main/install.sh | sh -s -- -b /usr/local/bin`
* `grype db update`
* `grype dir:/`

**Anything else we need to know?**:

**Environment**:
- Output of `grype version`:
```
Application:          grype
Version:              0.12.1
BuildDate:            2021-05-25T18:17:35Z
GitCommit:            7bdfffb43dcf75bfd4c8a3eec8f8ee0e2b97ab01
GitTreeState:         clean
Platform:             linux/amd64
GoVersion:            go1.16.4
Compiler:             gc
Supported DB Schema:  2
```
- OS (e.g: `cat /etc/os-release` or similar): `debian:9`

**Comment by luhring** [comment]
Thanks @Karreg. This issue has the same root cause as https://github.com/anchore/syft/issues/283.

One clarification — it's not that the scan takes "forever", it's that it runs for a (very) long time. The code isn't stuck in a loop, or hanging on a system call, or anything like that. It's just there's a large amount of IO-bound work the scanner needs to do (given the current implementation), and this work just takes a very long time (hours or even days).

This is definitely something we intend to address. We've talked internally about a few strategies (creating an FS index, introducing concurrency, and a few others).

**Comment by Karreg** [comment]
Thanks for the feedback. My technical timeout being 1 hour, it seems forever to me :D
Also, since I use trivy in parallel, the same command takes a few second. I did not think that it would be an execution time issue...

I will keep an eye on this issue. Thanks.

**Comment by wagoodman** [comment]
@Karreg try out v0.16.0 of grype, you should notice a dramatic difference:
```
# from within a container
[root@f49ab7b647c0 /]# time grype dir:/ > 
 ✔ Vulnerability DB        [no update available]
 ✔ Indexed /
 ✔ Cataloged packages      [170 packages]
 ✔ Scanned image           [672 vulnerabilities]

...

real	0m2.373s
user	0m1.891s
sys	0m0.509s
```

**Comment by Karreg** [comment]
Hello @wagoodman

I have tested it, and indeed, the scan is working fine and fast. Thanks! :)
