### ISSUE TITLE
Grype generates different results when using syft directly or if getting syft input from pipe

### ISSUE THREAD

**Issue by wlfshmn** [anchore/grype#354]
**What happened**:

I normally invoke grype based on stored output from syft as a performance improvement as I use the syft output for multiple checks and this saves me additional invocations of syft.

I noticed however that the virtualPAth data from syft on java archives does not transfer over when using the piped invocation but does get populated correctly when syft is used internally in grype. Investigation shows that there are also differences in the cpu generation in the two scenarios.

**What you expected to happen**:

I expect the two invocation scenarios to result in the same output, assuming the same version of syft is used internally in grype and int he piped invocation.

**How to reproduce it (as minimally and precisely as possible)**:

```
$ syft springio/gs-spring-boot-docker:latest -o json | /usr/local/bin/grype -o json > grype-with-pipe-from-syft.txt
$ grype springio/gs-spring-boot-docker:latest -o json > grype-direct.txt
$ diff grype-direct.txt grype-with-pipe-from-syft.txt | wc -l
896
```
Files attached.
[grype-with-pipe-from-syft.txt.gz](https://github.com/anchore/grype/files/6749178/grype-with-pipe-from-syft.txt.gz)
[grype-direct.txt.gz](https://github.com/anchore/grype/files/6749177/grype-direct.txt.gz)
[diff.txt.gz](https://github.com/anchore/grype/files/6749176/diff.txt.gz)

**Anything else we need to know?**:

**Environment**:
```
$ syft version
Application:   syft
Version:       0.15.1
BuildDate:     2021-04-22T20:55:47Z
GitCommit:     032cecbe7f19ca6f6f07d80f8dc902530e4c7502
GitTreeState:  clean
Platform:      linux/amd64
GoVersion:     go1.16.3
Compiler:      gc

$ grype version
Application:          grype
Version:              0.13.0
BuildDate:            2021-06-02T01:57:12Z
GitCommit:            3d21b8397d65770d292184b09a4f676bce6f3ec8
GitTreeState:         clean
Platform:             linux/amd64
GoVersion:            go1.16.4
Compiler:             gc
Supported DB Schema:  3

Syft 0.15. was used to match the version included in this version of Grype. Updating to the most recent syft makes no differences to the cpe or virtualPath properties, and only adds additional information like licenses that were missing in both cases before.

**Comment by dakaneye** [comment]
Hi @wlfshmn, thanks for reporting this issue. I was able to reproduce it on my local system (see below), and definitely think there’s a bug somewhere.

**Version Summary:**
Grype 0.13.0 uses syft 0.16.2

Standalone Syft version in this reported  issue is 0.15.1

Even when my local syft is the same version as what grype is using internally,  (0.16.2), there is a difference in the output.

@luhring & @wagoodman 

After looking through the code, I can see that there are two different package providers for grype, depending on whether the input is piped in or not. As you noted, the differences appear to be with two fields:
Package CPE in the reported vulns
Virtual Path of the package in the reported vulns

**Virtual Path Difference**
From what I can tell about how the Syft JSON Provider works (the one that’s used when piped syft input is provided), the reason that the Virtual Path is different is because it’s not included in the `packageBasicMetadata` struct fields (because this provider uses a simpler syft data structure than the real thing). To me, this makes sense because in the diff, the Virtual Path is mostly empty in the piped case.

**CPE field difference**
Upon inspection of the diff output, I did notice that it does look like some escaping is occurring (as the main difference between the two outputs). As far as I can tell, nothing is actually different between the two fields.

Tracking this down, it looks like grype is actually using the syft `pkg.cpe` code to deserialize the CPE strings from the JSON input. It looks like the syft JSON provider is stripping the slashes, whereas those probably aren’t getting stripped when we call the syft library directly and it generates the CPEs on its own

**Comment by dakaneye** [comment]
Looking at this again, I think my previous statement was a little off:
> From what I can tell about how the Syft JSON Provider works (the one that’s used when piped syft input is provided), the reason that the Virtual Path is different is because it’s not included in the packageBasicMetadata struct fields (because this provider uses a simpler syft data structure than the real thing). To me, this makes sense because in the diff, the Virtual Path is mostly empty in the piped case.

I do see that there's a custom java metadata parser that includes the virtual path. Will update this comment with more details as I continue investigating

**Comment by joshbressers** [comment]
I am no longer seeing this bug. I suspect it was fixed sometime in the last year. If you can reproduce this please reopen the issue.
