### ISSUE TITLE
Should Amazon Linux match vulnerabilities with NVD entries. 

### ISSUE THREAD

**Issue by hev** [anchore/grype#368]
**What would you like to be added**:
Similar to how Alpine linux also includes vulnerability matches from NVD, should Amazon linux do the same? 

**Why is this needed**:
It's unclear to me that the Amazon Linux feed functions the same way. Looking for more evidence of this to confirm. If so, when Amazon Linux is detected matches against NVD data should be surfaced.

**Comment by zhill** [comment]
The Amazon linux security team releases advisories when patches are available. The ask is to also match any NVD-based CVE if the current Amazon linux sec DB does not have an advisory that references that CVE so that an impacting-but-not-fixed vulnerability can be reported.

This will likely create more false-positives since NVD may not have the correct CPE for the Amazon linux package itself (only the upstream project), but there is value in having a conservative approach to indicate potential unfixed vulnerabilities. That is the approach currently taken with the Alpine SecDB which has a similar process.

**Comment by zhill** [comment]
The difference in Alpine vs Amazon is that the Amazon ALAS records use their own IDs, so we'll have to cross-reference the CVE references inside each against the NVD findings rather than the direct record IDs as we did with Alpine since those were CVEs.

**Comment by mattlorimor** [comment]
Amazon Linux package version numbers can also be different enough that looking at NVD to try to cross reference against Amazon Linux package versions is not straightforward. I would prefer to see ALAS start to behave like the RHEL Security Advisories where they issue ALAS advisories for unfixed CVEs.

**Comment by tgerla** [comment]
We're looking through some old issues and we're going to go ahead and close this issue. If anyone is having specific issues with Amazon Linux vulnerability matching please go ahead and file a new issue with details and we will be happy to take a look. Thank you!
