### ISSUE TITLE
Missed vulnerabilities in scanning

### ISSUE THREAD

**Issue by phocheng** [anchore/grype#377]
**What happened**:
As title, by using Grype and another scanning tool (gets its CVE information from the National Vulnerability Database (NVD)) scan the same bom file, we found there are many vulnerabilities missed in Grype's report. For example:

| Component | Version | Release | Supplier | CVE | Description | SIR |
| -- | -- | -- | -- | -- | -- | -- |
| libpcre | 2:8.39 | -12build1 |   | CVE-2019-20838 | libpcre in PCRE before 8.43 allows a subject buffer over-read in … | High |
| python | 3.6.7 | -1~18.04 |    | CVE-2019-9636 | Python 2.7.x through 2.7.16 and 3.x through 3.7.2 is affected by:… | Critical |

**What you expected to happen**:
Check why there is such discrepancies. Hopefully we could get a consistent report, at least, don't miss anything.

**How to reproduce it (as minimally and precisely as possible)**:
use this bom file to scan [bom.txt](https://github.com/anchore/grype/files/6972511/bom.txt)
Grype scanning result [vul.txt](https://github.com/anchore/grype/files/6972518/vul.txt) doesn't include the 1st vulnerability in my example list.

**Anything else we need to know?**:
No

**Environment**:
- Output of `grype version`:
% grype version
Application:          grype
Version:              0.15.0
BuildDate:            2021-07-14T15:37:24Z
GitCommit:            283bd3be5f586c9651b38089460f327db4860e45
GitTreeState:         clean
Platform:             darwin/amd64
GoVersion:            go1.16.5
Compiler:             gc
Supported DB Schema:  3

- OS (e.g: `cat /etc/os-release` or similar):
ubuntu 20.04

**Comment by luhring** [comment]
Hi @phocheng, thanks for the issue! I'll address the two vulnerability findings you mention separately...

## libpcre: CVE-2019-20838

>Grype scanning result vul.txt doesn't include the 1st vulnerability in my example list.

When I look at the `vul.txt` file you've provided, I do see this vulnerability present the output. Here's the command I ran to check this:

```
cat vul.txt | jq '.matches | map(select(.vulnerability.id == "CVE-2019-20838"))'
```

Here's the output I see for that command:

```jsonc
[
  {
    "vulnerability": {
      "id": "CVE-2019-20838",
      "dataSource": "http://people.ubuntu.com/~ubuntu-security/cve/CVE-2019-20838",
      "namespace": "ubuntu:20.04",
      "severity": "Low",
      "urls": [
        "http://people.ubuntu.com/~ubuntu-security/cve/CVE-2019-20838"
      ],
      "cvss": [],
      "fix": {
        "versions": [],
        "state": "not-fixed"
      },
      "advisories": []
    },
    "relatedVulnerabilities": [
      {
        "id": "CVE-2019-20838",
        "dataSource": "https://nvd.nist.gov/vuln/detail/CVE-2019-20838",
        "namespace": "nvd",
        "severity": "High",
// ...
```

From this output, you'll notice a few things:

1. Grype's output does include a match for CVE-2019-20838 (shown above).
2. Grype's output shows that this vulnerability record was sourced from Ubuntu's data (see the first `dataSource` field above), **AND** that it corresponds with an NVD vulnerability record for the same CVE (see the `relatedVulnerabilities` field above).

You might also notice that while NVD's record shows the severity for this CVE as `High`, Ubuntu's data shows the severity as `Low`. Why is Grype showing these values like this? Although Grype's output includes both values (shown above), Grype is designed to prefer data from the vendor directly _over_ NVD data. Vendors of software (like Ubuntu) pay close attention to CVEs that affect their software, and they have the most context to assess the impact of the vulnerability _specifically on their systems_ — whereas the data in NVD is significantly less refined and scrutinized.

## python: CVE-2019-9636

It looks like there's no installation of Python shown in the Syft SBOM you've attached (`bom.txt`). This means Grype wouldn't be able to match any vulnerabilities to Python for that input source.

If Python is present in the image you scanned, this might actually mean there's a problem in [Syft](https://github.com/anchore/syft)...

It looks like you're scanning the image `containers.cisco.com/build-and-deploy/swarm-worker:latest`, but that image isn't publicly available, so we can't troubleshoot using it. In order to move forward with investigating this, **we'd need you to do one of the following**:

1. Share this image with us
2. If you can't share this image, produce a similar image (with Python installed using the same method as was used in the image you originally scanned) and share _that_ image with us.
3. Tell us more about why you believe Python is present in the container image, such that we have enough information to reproduce in a new container image we build.

Thanks for your assistance in helping us figure this out!

**Comment by spiffcs** [comment]
Closing this issue as stale. Thanks again for showing us possible false negatives in grype!

If you need further clarification beyond the above comment let me know and I can keep investigating your case.
