### ISSUE TITLE
Support CycloneDX as SBOM input to grype

### ISSUE THREAD

**Issue by hectorj2f** [anchore/grype#481]
**What would you like to be added**:
We are using grype but our generated SBOM files are not always generated by Syft. We'd like to understand what is needed to accept this standard format.

**Why is this needed**:
To accept commonly used format for the generation of BOM.

**Additional context**:

We saw in the README that is part of the future plans. However the proliferation of tools creating SBOM files following the standard formats represents a blocker to continue using grype.

**Comment by wagoodman** [comment]
A compromise here when it comes to getting the feature in (enabling input from SBOMs in different formats) and the quality of the vulnerability matching... there is a good change that matching will predictably be lower for other formats until we better understand how the information can be encoded in the other SBOM formats (SPDX and CycloneDX). In order to get some forward progress here, I think it makes sense to log warnings in cases where we know the matching could be lower. That is, we shouldn't require on-par matching quality to that of the Syft JSON input in order for this issue to be complete.

**Comment by hectorj2f** [comment]
@wagoodman yes, it makes sense to me. I am happy to get involved on a WG to investigate what we need from these formats to get the same or better accuracy.

**Comment by samj1912** [comment]
Related - https://github.com/anchore/syft/pull/710#issuecomment-1006943111

**Comment by kzantow** [comment]
Notes from an offline conversation with @wagoodman 

In order to support import of alternative SBOM formats, we will need a particular set of data for Grype to perform ideal matching: **package name**, **package version**, **package vendor**, **os distribution**, and **CPEs** (I may have missed something here). However, it is likely that imported SBOMs will be missing some of this information and we'd still like for Grype to be as useful as possible. Some ideas for handling this are:

**package name** & **package version**: this is pretty much required and we will simply return an error if this isn't provided for anything

**package vendor**: being included somehow could contribute to CPE generation, if no CPEs are provided

**CPEs** if missing:
* simply notify the user that no CPE matching is happening
* automatically attempt to generate these based on the available package information
* notify the user no CPE matching is happening but also provide a command line flag to automatically generate them

**os distribution**:
* notify the user no distro matching is happening
* notify the user no distro matching happens and provide a flag to search across _all_ distros (this may be very noisy)
* allow the user to specify a distro hit via normal configuration
* enhance PURLs to include enough information to reasonably determine the distro
* accept a distribution hint in some metadata location as idiomatic to the input format as possible

In all of these cases, we should probably document how matching happens in the event of missing data and how a vendor could provide this information so Grype would have improved matching.

**Comment by xtreme-conor-nosal** [comment]
vendor should map to the author/publisher/supplier fields of a component (if provided)

For the distribution, is a version required, or is "distro family" a useful-enough hint? (e.g. if component purls are present and have a `pkg:deb/debian` prefix as syft currently outputs)

I like the approach of doing the best with what we have, and log warnings if appropriate.
