### ISSUE TITLE
Grype scan issue "unexpected page size"

### ISSUE THREAD

**Issue by vchinchambekar** [anchore/grype#525]
Hi All,

I was trying to scan docker image tar file 1.2GB size and getting "unexpected page size" error.
Could you guys help me on this issue. Thanks in advance.

----------------------------------------------------------------
 ✔ Vulnerability DB        [no update available]
New version of grype is available: 0.27.0
 ✔ Parsed image
 ⠏ Cataloging packages     [packages 0]
1 error occurred:
        * failed to catalog: 1 error occurred:
        * unable to catalog rpmdb package=/var/lib/rpm/Packages: unexpected page size: 1048576
-------------------------------------------------------------------

**Comment by spiffcs** [comment]
I think it’s coming from here:
https://github.com/anchore/syft/blob/da0b17b719b6d5cabe0819d44f90755c73312de8/syft/pkg/cataloger/rpmdb/parse_rpmdb.go#L37-L45

When opening the rpmdb valid page sizes include. So the value reported in your error is 16 times the max page size value.
```
var validPageSizes = map[uint32]struct{}{
	512:   {},
	1024:  {},
	2048:  {},
	4096:  {},
	8192:  {},
	16384: {},
	32768: {},
	65536: {},
}
```

This library was forked which provides some of that functionality:
https://github.com/knqyf263/go-rpmdb
https://github.com/knqyf263/go-rpmdb/blob/master/pkg/bdb/bdb.go

**Comment by wagoodman** [comment]
This may indicate that the DB is corrupted or that the validation is missing a case here, it's not quite clear which way yet. @vchinchambekar Can you provide the image you used to produce this error? (Or provide an image you can share that reproduces this problem if you can't share your image)

I think I need to dig into Berkeley DB design details to understand more before speculating further.

**Comment by vchinchambekar** [comment]
Hi @wagoodman @spiffcs,
Thanks for your update but we can not share this official customized docker image.
Do you have any other solution to look on this ??

Not:- FYI other images I'm able to get scan report.

**Comment by spiffcs** [comment]
@vchinchambekar I think it's because Berkely DB specifies that the maximum database page size is `65536` (64k)[^1] .

Without the image, it's harder to go further than that.  RPMDB uses Berkely under the hood so I would investigate if the DB is corrupted or what is causing the package database to be so large.

Here is a quick starting point that might point to how the package database for that image has gotten so large:
https://access.redhat.com/solutions/4543461

[^1]: https://docs.oracle.com/database/bdb181/html/programmer_reference/am_misc_dbsizes.html

**Comment by luhring** [comment]
Checking in to see if we have a way to reproduce the problem. If not, no worries, we can close this issue for now.

**Comment by rightblank** [comment]
Hi, We run across this same issue with the same exact error message, and the db looks fine.
```
[root@db96f4b94c2d ~]#  ls -sail /var/lib/rpm/Packages 
2491022 15600 -rw-r--r-- 1 root root 15974400 Jan 21 16:39 /var/lib/rpm/Packages
[root@db96f4b94c2d ~]#  /usr/lib/rpm/rpmdb_verify /var/lib/rpm/Packages
BDB5105 Verification of /var/lib/rpm/Packages succeeded.
```

```
* unable to catalog rpmdb package=/var/lib/rpm/Packages: unexpected page size: 1048576
```
And there is a similar related issue. https://github.com/anchore/syft/issues/784.

**Comment by rightblank** [comment]
Hi, I just figured out that the code read the file with LittleEndian while actually our platform is s390x which uses BigEndian. that's why it interprets the page size from 4096 to 1048576.
https://github.com/knqyf263/go-rpmdb/blob/730f48726ee618c9d0ef021c5a4e668222e35c6e/pkg/bdb/hash_metadata_page.go#L24

**Comment by spiffcs** [comment]
Thanks @rightblank! I think we're going to close this for now since it's in a downstream library from Grype. I'll open an issue with `go-rpmdb` and see if we can get this hardcoded value to be a bit smarter and recognize the platform to select which endian value to substitute in.
