### ISSUE TITLE
Vulnerabilities CVE-2021-44790 and CVE-2021-44224 not identified

### ISSUE THREAD

**Issue by leonidsandler** [anchore/grype#571]
Even though I can see that both of these CVEs are present in the vulnerability .db, they are not showing up in the scan results of the Apache HTTPD (image httpd:2.4.51).

**Comment by kzantow** [comment]
Sorry this doesn't answer the question yet, but just noting a little investigation:

CPEs in those vulnerabilities are using `cpe:2.3:a:apache:http_server:...`

There are no `http_server` or even `httpd` CPEs generated from this image, the only thing remotely related seems to be:
```
      "name": "libnghttp2-14",
      "version": "1.43.0-1",
      "cpes": [
        "cpe:2.3:a:libnghttp2-14:libnghttp2-14:1.43.0-1:*:*:*:*:*:*:*",
        "cpe:2.3:a:libnghttp2-14:libnghttp2_14:1.43.0-1:*:*:*:*:*:*:*",
        "cpe:2.3:a:libnghttp2_14:libnghttp2-14:1.43.0-1:*:*:*:*:*:*:*",
        "cpe:2.3:a:libnghttp2_14:libnghttp2_14:1.43.0-1:*:*:*:*:*:*:*",
        "cpe:2.3:a:libnghttp2:libnghttp2-14:1.43.0-1:*:*:*:*:*:*:*",
        "cpe:2.3:a:libnghttp2:libnghttp2_14:1.43.0-1:*:*:*:*:*:*:*"
      ],
 ```

**Comment by leonidsandler** [comment]
Is there something I can help with?

**Comment by kzantow** [comment]
@leonidsandler not just yet, thank you! The issue is we don't have anything specifically to match on in the image. I don't think this is an isolated situation. To solve this and related misses I have a few ideas I'm running by the team but they might take a bit of time to get implemented.

**Comment by leonidsandler** [comment]
Just a curiosity, do you mean that there is no universal way to identify the version number of httpd file?

**Comment by kzantow** [comment]
The problem is less the version and more the package. The way Grype scans things, it generates CPEs to match against the CPEs provided by NVD (among other things) - for example examine the [CPEs here](https://nvd.nist.gov/vuln/detail/CVE-2021-44224). In this case, there is nothing that Grype finds that resolves to a CPE including `...:apache:http_server:...`, so there's nothing to match against the NVD data this way. This is likely to do with the way the container is packaged and the fact there is no `http_server` as such in the debian package list.

**Comment by leonidsandler** [comment]
Hi, any news on this? I think this particular CVE is no longer a high priority threat, but I was wondering if potential attacker can change a name or some other packaging convention to avoid CVE detections in the future. Would you be open to share this problem was? Thank you!

**Comment by Anonimo501** [comment]
Hola.
 Yo tambien estoy en la búsqueda de algún exploit o código que pueda vulnerar CVE-2021-44224 y CVE-2021-44790, si alguien sabe de algo lo agradecería mucho.

Saludos.

**Comment by spiffcs** [comment]
Just to close this out, the main reason this is not being detected is in the generated SBOM syft does not have a binary cataloger that can identify `httpd`

On the other topic of renaming packages or data to circumvent detection, that could happen, but it is not what is occurring in this case. Grype is not missing this because of a misname or a contradiction with the vulnerability data, it's just that the binary is not included in the generated sbom. We hope to have binary support in the future see https://github.com/anchore/syft/issues/661 for more information on how we want to include this in the SBOM. Also https://github.com/anchore/syft/issues/524 could tangentially be related.

**Comment by fazalumrani86-byte** [comment]
Mujhe exploit chaeye
