### ISSUE TITLE
add basic instructions for compiling binaries to install readme

### ISSUE THREAD

**Issue by fmtbkgiddiqq** [anchore/grype#581]
**What would you like to be added**:

Please add some basic instructions for compiling the binaries to the install readme as an alternative to curl to bash. 

**Why is this needed**:

Some folks are uncomfortable with the security implications of curl to bash

There are additional use cases where users may wish to modify the functionality of the project to better fit their needs

**Additional context**:

**Comment by kzantow** [comment]
This is a good idea. There is a [CONTRIBUTING.md](https://github.com/anchore/grype/blob/main/CONTRIBUTING.md) but it doesn't explicitly say this. However, just so you know: being a fairly standard `go` project, you should be able to build it with just `go build`, which doesn't actually work because there is a `grype` directory. But instead you can use `go build main.go` and it will output a `main` binary, which you can rename/use/etc.
