### ISSUE TITLE
How can grype scan manually installed dependencies?

### ISSUE THREAD

**Issue by ssproessig-thales** [anchore/grype#651]
When creating an image we have two manual steps:
- add Oracle Instance Client (by unpacking `instantclient-basiclite-linux.x64-xxxxx.zip` in `/opt`)
- add a compiled Python application to `/app` - this comes with `.pyc` files of the application and its Python virtual env with the dependencies

It would be cool if I could point `grype` to those directories for it to index them as well.

**Comment by spiffcs** [comment]
Hey @ssproessig-thales! I don't think we currently have a binary cataloger for these applications in syft. Grype is not the program that generates the SBOM. It uses syft to build the bill of materials and then does the vulnerability matching against that document.

I'm going to close this issue in grype, but link you to a related issue in syft that might be what you're looking for.

https://github.com/anchore/syft/issues/31

Here we discuss adding a hints file so that if we come across software syft cannot detect users are able to annotate the sbom with any pre-knowledge about the components
