### ISSUE TITLE
Include package URL purl in grype cyclonedx output

### ISSUE THREAD

**Issue by mkesper** [anchore/grype#660]
**What would you like to be added**:

Grype CycloneDX output should include "purl" package URL information which is already present in syft output.

**Why is this needed**:

To give other tools a firm base for connecting their own information.
E.g. [Sonatype states](https://help.sonatype.com/iqserver/analysis/cyclonedx-application-analysis): When specifying components using its Package URL (tag <purl>), IQ Server will try to match it with its own data and find all information about it.

**Comment by spiffcs** [comment]
Thanks @mkesper! This looks like a pretty quick addition since it fits right under the `component.purl`.

I think we can go a step further and make sure our syft component should == our grype component and right now those don't line up.

We've pulled this issue forward to account for those differences and should have a patch working to get this updated in grype soon.

**Comment by tgerla** [comment]
Hi @mkesper, we're going through some old tickets and we have confirmed this request has been implemented. If you have a chance, can you try it out with the latest version of Grype? If you have any trouble, let us know. Thanks!
