### ISSUE TITLE
Grype reports some critical Vault CVE on itself

### ISSUE THREAD

**Issue by jswager-cisco** [anchore/grype#676]
**What happened**:
Installed Grype in a Docker image using the published installation instructions.

**What you expected to happen**:
Grype would not trigger any Critical vulnerabilities on itself.

**How to reproduce it (as minimally and precisely as possible)**:
Adding this to a typical Ubuntu based Docker image:
```
ARG BIN_DIR=/usr/local/bin
RUN curl -sSfL https://raw.githubusercontent.com/anchore/grype/main/install.sh  | sh -s -- -b $BIN_DIR
RUN grype db update
```
Then run "grype" on the resulting image and search for Critical vulnerabilities.

**Anything else we need to know?**:
The latest grype database is being used.  The list of CVEs that were reported:
- CVE-2020-12757
- CVE-2020-16250
- CVE-2020-16251
- CVE-2022-0543

**Environment**:
- Output of `grype version`:
```
$ grype version
Application:          grype
Version:              0.34.1
Syft Version:         v0.41.4
BuildDate:            2022-03-15T14:10:38Z
GitCommit:            0b76016235332f66ceac7e266c0278b86d3a23cf
GitDescription:       v0.34.1
Platform:             linux/amd64
GoVersion:            go1.17.7
Compiler:             gc
Supported DB Schema:  3
```

- OS (e.g: `cat /etc/os-release` or similar):
WSL2, Ubuntu 20.04

**Comment by westonsteimel** [comment]
Yeah, this is because syft pulls in sigstore as a dependency now, and grype depends on syft.  I think maybe @spiffcs was looking into this?

**Comment by jswager-cisco** [comment]
@spiffcs - using `ubuntu:20.04`

And my apologies, I didn't report fully accurately.  We are installing syft in the image too:
`RUN curl -sSfL https://raw.githubusercontent.com/anchore/syft/main/install.sh   | sh -s -- -b $BIN_DIR`

I might be wrong in that it's not a grype problem, but a syft problem.  Although, I do see - github.com/hashicorp/vault/api v1.4.1 here https://github.com/anchore/grype/blob/main/go.sum#L1266 - but is that something grype adds or something imported from syft, I'm not sufficiently GoLang proficient to know.

**Comment by westonsteimel** [comment]
So, I have definitely encountered those results with syft `v0.39.3`, and just looked and looks like `v0.41.6` has same results

```sh
$ docker run --rm anchore/grype:v0.34.3 anchore/syft:v0.41.6
[0004]  WARN some package(s) are missing CPEs. This may result in missing vulnerabilities. You may autogenerate these using: --add-cpes-if-none
[0005]  WARN Unable to determine the OS distribution. This may result in missing vulnerabilities. You may specify a distro using: --distro <distro>:<version>
NAME                                 INSTALLED  FIXED-IN  VULNERABILITY   SEVERITY
github.com/hashicorp/vault/api       v1.4.1               CVE-2020-13223  High
github.com/hashicorp/vault/api       v1.4.1               CVE-2020-16250  Critical
github.com/hashicorp/vault/api       v1.4.1               CVE-2021-27668  Medium
github.com/hashicorp/vault/api       v1.4.1               CVE-2021-38554  Medium
github.com/hashicorp/vault/api       v1.4.1               CVE-2021-41802  Medium
github.com/hashicorp/vault/api       v1.4.1               CVE-2021-45042  Medium
github.com/hashicorp/vault/api       v1.4.1               CVE-2020-16251  Critical
github.com/hashicorp/vault/api       v1.4.1               CVE-2020-25816  Medium
github.com/hashicorp/vault/api       v1.4.1               CVE-2021-3024   Medium
github.com/hashicorp/vault/api       v1.4.1               CVE-2021-38553  Medium
github.com/hashicorp/vault/api       v1.4.1               CVE-2020-12757  Critical
github.com/hashicorp/vault/api       v1.4.1               CVE-2020-25594  Medium
github.com/hashicorp/vault/api       v1.4.1               CVE-2021-27400  High
github.com/hashicorp/vault/api       v1.4.1               CVE-2021-32923  High
github.com/hashicorp/vault/api       v1.4.1               CVE-2021-43998  Medium
github.com/hashicorp/vault/sdk       v0.4.1               CVE-2018-19786  High
github.com/hashicorp/vault/sdk       v0.4.1               CVE-2020-25594  Medium
github.com/hashicorp/vault/sdk       v0.4.1               CVE-2021-3024   Medium
github.com/hashicorp/vault/sdk       v0.4.1               CVE-2021-41802  Medium
github.com/hashicorp/vault/sdk       v0.4.1               CVE-2020-13223  High
github.com/hashicorp/vault/sdk       v0.4.1               CVE-2021-38554  Medium
github.com/hashicorp/vault/sdk       v0.4.1               CVE-2021-27400  High
github.com/prometheus/client_golang  v1.11.0              CVE-2022-21698  High
google.golang.org/protobuf           v1.27.1              CVE-2021-22570  High
google.golang.org/protobuf           v1.27.1              CVE-2015-5237   High
```

**Comment by spiffcs** [comment]
Thanks @westonsteimel for the command. I've got the same locally. I'm going through each of these to be sure they are FP matching to generically against `"cpe:2.3:a:hashicorp:vault:v1.4.1:*:*:*:*:*:*:*"` rather than `vault-api`

**Comment by wagoodman** [comment]
https://github.com/anchore/grype/issues/676#issuecomment-1071185031 essentially explains the behavior we're seeing; The CVE is for `hashicorp/vault` and not the go submodule `hashicorp/vault/api`, which share the same git repo, but different version lineages:

<img width="479" alt="Screen Shot 2022-03-18 at 9 58 57 AM" src="https://user-images.githubusercontent.com/590471/159016569-178499dc-4614-44fd-926c-67a60db5acd5.png">

Note that `v1.4.1` and `api/v1.4.1` are for different commits and are years apart.

_`<aside about go submodules>`_
The reason why you make a go module in general is to declare that a set of packages are versioned together. When it comes to git being the VCS used for a go module, the version corresponds with a git tag (and [that git tag should be properly formatted](https://go.dev/ref/mod#versions)).

When you make a go submodule, which is multiple go modules in the same repo, how do you version these independently if they share the same git tags? Apparently the go tooling / proxy / (or something inbetween) accounts for this already; the answer is that the path of the submodule in the source repo should be prefixed to the git tag. Some examples of this:

- Your typical go module
```
Go module path: github.com/hashicorp/vault
Go module version: v1.4.1
Git repo: https://github.com/hashicorp/vault
Git tag: v1.4.1
```

- A go submodule
```
Go module path: github.com/hashicorp/vault/api
Go module version: v1.4.1
Git repo: https://github.com/hashicorp/vault
Git tag: api/v1.4.1
```

To get a better sense of the version lineages available for both go modules we can use the go proxy to see what has already been cached:
```
# for vault/api...
$ curl -s https://proxy.golang.org/github.com/hashicorp/vault/api/@v/list | wc -l
      12

# for vault...
$ curl -s https://proxy.golang.org/github.com/hashicorp/vault/@v/list | wc -l
     164
```

Note the drastically different count here. Also we can compare this to tags in the repo that match `api/v`:
```
$ curl -s https://proxy.golang.org/github.com/hashicorp/vault/api/@v/list | sort
v0.4.0
v1.0.1
v1.0.2
v1.0.3
v1.0.4
v1.1.0
v1.1.1
v1.2.0
v1.3.0
v1.3.1
v1.4.0
v1.4.1

$ git tag | grep 'api/v'
api/v1.0.1
api/v1.0.2
api/v1.0.3
api/v1.0.4
api/v1.1.0
api/v1.1.1
api/v1.2.0
api/v1.3.0
api/v1.3.1
api/v1.4.0
api/v1.4.1
```

Other than `v0.4.0`, which git tag may have been deleted from git, these match up!

_`</aside about go submodules>`_

Why are we crafting CPEs for `hashcorp/vault` when this is really for `hashicorp/vault/api`? Grype's matching philosophy (and that of anchore-engine) is to try and match software components with the upstream or umbrella project that they belong to, since CVEs tend to be written against these upstream/larger projects and not against every single sub-component. This is not perfect and is known to lead to false positives, however, tends to be better than not following this philosophy (from trial and error).

That being said, I think there should be an exception for the go ecosystem. Given the information about go modules naturally having different version lineages heavily hints at not using the typical "match agains the umbrella project" philosophy. Why? For go, in the circumstance where a CVE is written for a "root"-level go module, and we declare that submodules can be identified as the same modules as the root-level go module, then we are guaranteed to make the wrong decision, since the vulnerable version listed on the CVE is for inherently different software.

What does this mean for syft? We should make a change to the CPE generation logic in syft that excludes go-packages from crafting CPEs for upstream projects. 

Making this syft change and upgrading the syft version used in grype would deselect these `vault/api` and `vault/sdk` false positives when scanning grype against itself.

**Comment by jonasagx** [comment]
This issue is fixed in grype with https://github.com/anchore/grype/pull/761 merged.
