### ISSUE TITLE
Java JDK 8 framework version not detected correctly

### ISSUE THREAD

**Issue by markbastiaans** [anchore/grype#750]
**What happened**:
I'm scanning a CycloneDX SBOM with the following component:
```
        {
            "type": "framework",
            "name": "java.8-jdk",
            "version": "1.8.0.332",
            "publisher": "Adoptium",
            "cpe": "cpe:2.3:a:oracle:jdk:1.8.0:update332:*:*:*:*:*:*",
            "purl": "pkg:generic/adoptium-jdk@1.8.0.332?arch=amd64"
        }
```

Grype does not detect the version correctly: it apparently does not take the `update332` into account in the scan results, and finds all vulnerabilities for any JDK with version 1.8.0.

Note that `cpe:2.3:a:oracle:jdk:1.8.0:update332:*:*:*:*:*:*` is the "official" CPE as listed in the NIST NVD database for the JDK framework.

**What you expected to happen**:
In this case, find no vulnerabilities (8u332 is the latest version without major CVEs).

**How to reproduce it (as minimally and precisely as possible)**:
Create a minimal CycloneDX SBOM with the component specified, and use `grype sbom:<filename>` to scan it.

**Anything else we need to know?**:
No

**Environment**:
- Output of `grype version`: `0.37.0`
- OS (e.g: `cat /etc/os-release` or similar):
```
ProductName:	macOS
ProductVersion:	11.6.4
BuildVersion:	20G417
```

**Comment by willmurphyscode** [comment]
Hi @markbastiaans, thanks for reporting this! I've made the SBOM you suggested (changing to `update371`, since that's the latest one), and I definitely see a lot of JDK 1.8 vulnerabilities, but I'm not sure which ones should be considered false positives. Here's one that might be:

CVE-2022-21248 from https://nvd.nist.gov/vuln/detail/CVE-2022-21248
matched artifact is:
   java.8-jdk - pkg:generic/adoptium-jdk@1.8.0.371?arch=amd64
match type is cpe-match
CPEs 
  - `cpe:2.3:a:oracle:jdk:1.8.0:update371:*:*:*:*:*:*`

URLs:
  - https://nvd.nist.gov/vuln/detail/CVE-2022-21248
  - https://lists.debian.org/debian-lts-announce/2022/02/msg00011.html
  - https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/2DIN3L6L3SVZK75CKW2GPSU4HIGZR7XG/
  - https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/4J2N4FNXW6JKJBWUZH6SNI2UHCZXQXCY/
  - https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/KPIWQ6DL5IPOT54UBWTISG5T24FQJ7MN/
  - https://security.gentoo.org/glsa/202209-05
  - https://security.netapp.com/advisory/ntap-20220121-0007/
  - https://www.debian.org/security/2022/dsa-5057
  - https://www.debian.org/security/2022/dsa-5058
  - https://www.oracle.com/security-alerts/cpujan2022.html

https://nvd.nist.gov/vuln/detail/CVE-2022-21248 has `cpe:2.3:a:oracle:jdk:1.8.0:update311:*:*:*:*:*:*`, which definitely seems both different and older than `cpe:2.3:a:oracle:jdk:1.8.0:update371:*:*:*:*:*:*`, so I think that's an example of the kind of issue you're reporting. I'll keep investigating. Thanks again for the report!

**Comment by willmurphyscode** [comment]
Hi @markbastiaans, I'm no longer able to reproduce this issue on the latest version of grype. Are you still experiencing this issue?

Output of `grype version` is:

```
Application:          grype
Version:              0.66.0
Syft Version:         v0.89.0
BuildDate:            2023-08-31T16:02:11Z
GitCommit:            brew
GitDescription:       [not provided]
Platform:             darwin/arm64
GoVersion:            go1.20.7
Compiler:             gc
Supported DB Schema:  5
```

**Comment by willmurphyscode** [comment]
Hi @markbastiaans, I'm closing this since I'm no longer able to reproduce it, and we haven't heard back from you. If we've missed something, please let us know!
