### ISSUE TITLE
False positive CVE-2016-0956

### ISSUE THREAD

**Issue by karthickm512** [anchore/grype#753]
**What happened**:
While scanning our software that packs Apache Karaf 4.3.7 (contains [org.apache.sling.commons.johnzon] 1.2.14), CVE-2016-0956 is reported

**What you expected to happen**:
As per NVD https://nvd.nist.gov/vuln/detail/CVE-2016-0956#match-3424223 , the impacted artifacts are apache.sling. till 1.0.12 while the available 3pp component and version present in target karaf is different. No issue should have been reported

**How to reproduce it (as minimally and precisely as possible)**:
Download Apache Karaf runtime 4.3.7 and scan using Anchore Grype

**Anything else we need to know?**:
No

**Environment**:
- Output of `grype version`: 0.37.0
- OS (e.g: `cat /etc/os-release` or similar): SLES 15.3

**Comment by karthickm512** [comment]
@luhring Any observations on this?

**Comment by karthickm512** [comment]
@spiffcs : Hi, any timelines/version suggested for this to be fixed?

**Comment by spiffcs** [comment]
Hey @karthickm512! Sorry for the frustration here on the false positives.

This is probably being caused by an over-aggressive match against a CPE generated for `Apache Karaf`.

We're trying to be very careful right now around changing the matching logic since any tweak in CPE generation could also turn into a patch that causes multiple false negatives aka: missing real vulnerabilities.

I apologize for not having a great timeline yet for you on when we'll have the ability to safely throw out these over-aggressive FP.

For now I've added it to our growing list of false positive issues so when we do start to make progress here we have a solid set of data to test against.

**Comment by tgerla** [comment]
I will go ahead and close this issue because it should be fixed by our recent switch to the GHSA database for some vulnerability matches. Please see https://anchore.com/blog/say-goodbye-to-false-positives/ for more details. If you have any more problems, feel free to re-open or open a new issue!
