### ISSUE TITLE
logs: enable application logs to a file (always)

### ISSUE THREAD

**Issue by alfredodeza** [anchore/grype#88]
We currently have a mix of nice, human-readable output like the download and check process when the tool starts and application logging that comes mostly in the form of errors. For example:

```
[0000] ERROR failed to catalog: could not fetch image 'foobar': unable to trace image save progress: unable to inspect image: Error: No such image: index.docker.io/library/foobar:latest
```

One of the problems that will happen when users face issues/bugs is that they will probably not run with high verbosity, and we will end up asking them to re-run with added verbosity flags (e.g. `-vvv`).  This will complicate the reporting of the issue because the run will most likely be long gone, and  the output no longer available.

Since the file logging is not enabled by default, asking for the log artifact will also not be a possibility. 

As a reporter, having to re-run while trying to reproduce, is cumbersome to say the least. 

Grype should enable file logging by default, and for a while after releasing, the default should be DEBUG. This highly verbose level should lower to INFO or WARNING as the tool stabilizes.

Enabling the file logging by default would also mean to do a "best effort" in trying to find a suitable locations, because `/var/log/grype/2020-08-04.log` might not be available or with enough permissions

In addition to all of this, it would be really useful to start separating what user-facing output is, vs. what system logging entails. More developer-like logs go to the file, and user-friendly messages go to the terminal

**Comment by wagoodman** [comment]
I can appreciate the desire to improve the user experience when it comes to troubleshooting, however, I want to point out some important distinctions in the above examples:

1. Regarding `/var/log`: `/var/log/` is by default not writable to anyone other than root in most (all?) linux distributions. I'm only aware of packages creating these directories and modifying sub-directory permissions at install type (e.g. during an RPM installation, as `ceph-osd` does [the provider of `ceph-volume`], which is always done as root) or by applications themselves running as root. Toolbox tools should be simple `curl`-and-run tools, which do not require root privileges. We do have deb/rpm packages, but shouldn't depend on those packages being used. It would be ideal to look for logs in one location, not several ("if you're on rhel/debian and installed via the deb/rpm look in `/var/log/grype` otherwise check in `/other/dir`..."). If the user decides to override the log location, that's OK, but default behavior should be easy and consistent.

2. On the theme of "do CLI tools write to disk": yes CLI tools often write to disk --there are also a class of CLI tools that do not. Just because tool X writes to disk doesn't automatically mean that we should too. I think we need to convince ourselves when it makes sense for the use case in question. The use case put forth in this issue is "should we always log by default to help users troubleshoot problems".

3. If we log by default, we own handling those logs. If it's in a local directory relative to invocation (like with `tox`) this seems simple enough --note that we will require users to add our local `./.grype/` scratch dir to their gitignore. If we decide to use a common directory for all invocations, then we will have relatively more responsibility on us (log rotation / cleanup, concurrent writes, etc) --we should try to avoid this unless we need to, as these fall outside of the `curl`-and-run requirements for this project.

4. Observations on grype behavior today: when running in a CI environment you automatically are getting info/error level events to the console (since there is no tty).

5. With regard to `it would be really useful to start separating what user-facing output is vs. what system logging entails` we already have an ETUI for user-facing feedback and a logger for system level-logging, with config and environment variables to write the logs to disk in a user-specified location. We should continue to evolve the output of the ETUI to handle all forms of output (errors are not covered today, and falls back to a logger interface... this topic is for another existing issue).

Given the above points, I want to put forth some opinions on this:
- I think logs for troubleshooting is awesome and helpful. I don't think the logs are required to be persisted on disk per-say.
- When running in your terminal (with a tty) you have the power to change the output to a logging format with `-vv` pretty simply. This means that we're really discussing users that are running in CI, which already default to a log format to the console (no `-v` necessary). 

With the above opinions, I feel that the discussion should really steer closer to "what should the default log level be" since a user running this without a tty already has logs directed to the console.

**Comment by alfredodeza** [comment]
>     1. Regarding `/var/log`: `/var/log/` is by default not writable to anyone other than root in most (all?) linux distributions. I'm only aware of packages creating these directories and modifying sub-directory permissions at install type (e.g. during an RPM installation, as `ceph-osd` does [the provider of `ceph-volume`], which is always done as root) or by applications themselves running as root. Toolbox tools should be simple `curl`-and-run tools, which do not require root privileges. We do have deb/rpm packages, but shouldn't depend on those packages being used. It would be ideal to look for logs in one location, not several ("if you're on rhel/debian and installed via the deb/rpm look in `/var/log/grype` otherwise check in `/other/dir`..."). If the user decides to override the log location, that's OK, but default behavior should be easy and consistent.

`/var/log` was an example to point how logging by default is useful. I agree that the default behavior should be easy and consistent. Using the current working directory or $HOME (or anything in between) would be fine.

> 
>     2. On the theme of "do CLI tools write to disk": yes CLI tools often write to disk --there are also a class of CLI tools that do not. Just because tool X writes to disk doesn't automatically mean that we should too. I think we need to convince ourselves when it makes sense for the use case in question. The use case put forth in this issue is "should we always log by default to help users troubleshoot problems".
> 

At this point in time, I think it would be troublesome not to write to disk. CI environments allow to collect artifacts and the `grype` log output as an artifact would be great to keep around. 

>     3. If we log by default, we own handling those logs. If it's in a local directory relative to invocation (like with `tox`) this seems simple enough --note that we will require users to add our local `./.grype/` scratch dir to their gitignore. If we decide to use a common directory for all invocations, then we will have relatively more responsibility on us (log rotation / cleanup, concurrent writes, etc) --we should try to avoid this unless we need to, as these fall outside of the `curl`-and-run requirements for this project.

This point reads more like the many options we can come up with related to usage. We don't need to require users to add `.grype` to `.gitignore` if this is configurable for example.  I would propose to go from simplest (e.g. Tox's approach to `.tox`) to complex: we own the rotation of logs. 

I don't think we need to prevent logging by default to disk because we might want log rotation. 

> 
>     4. Observations on grype behavior today: when running in a CI environment you automatically are getting info/error level events to the console (since there is no tty).

This is great today. And will help us when things are running on unknown environments, mostly on CI.

> 
> Given the above points, I want to put forth some opinions on this:
> 
>     * I think logs for troubleshooting is awesome and helpful. I don't think the logs are required to be persisted on disk per-say.
> 
>     * When running in your terminal (with a tty) you have the power to change the output to a logging format with `-vv` pretty simply. This means that we're really discussing users that are running in CI, which already default to a log format to the console (no `-v` necessary).
> 
> 
> With the above opinions, I feel that the discussion should really steer closer to "what should the default log level be" since a user running this without a tty already has logs directed to the console.

This is part of the problem with what we have today. I would strongly suggest that for now, it should be `DEBUG` levels of logging, since the tooling is brand-new, and we don't know enough of all the various environments this is going to be running on. 
But since the output is currently mixed with the user-facing messaging, it is way too verbose, causing noise. That amount of noise in a CI run wouldn't be as useful as having it separate on a file which can be looked at when there is a failure.

This could be avoided today with something like `grype myimage:latest > grype.log` but then that forces anyone that doesn't redirect to handle the high-verbosity output.

**Comment by wagoodman** [comment]
> since the output is currently mixed with the user-facing messaging

Just to clarify, when running in an environment without a TTY, only logging is shown (not the ETUI). There isn't a "mix" of user-facing messaging aside from the presenter report output. Specifically, all log output is to `stderr` and presenter report output is to `stdout`. So this command would give you the desired result:
```bash
grype myimage:latest 2> grype.log
```
Where the log file would contain only log entries and stdout would show the report.

> That amount of noise in a CI run wouldn't be as useful as having it separate on a file which can be looked at when there is a failure....

Today when there is no TTY we default to INFO level for the logger output, which already shows failures.

> ...then that forces anyone that doesn't redirect to handle the high-verbosity output.

Are we saying that the volume of output from DEBUG log level by default is too much for CI output?

**Comment by wagoodman** [comment]
I'm going to close this for now with some context:
- there is a way to log to disk in syft in an opt in capacity (`SYFT_LOG_FILE=/tmp/syft.log syft alpine:latest -vv`)
- at this point we won't be by-default writing logs to disk
