### ISSUE TITLE
False positive for CVE-2022-0839

### ISSUE THREAD

**Issue by nvp152** [anchore/grype#895]
**What happened:**
I have a container image with "FROM liquibase/liquibase:4.9.1" yet the scanner produces a finding for **CVE-2022-0839** for policy id **48e6f7d6-1765-11e8-b5f9-8b6f228548b6** indicating that a fix is available for 4.8.0. 

**What you expected to happen**
This isn't correct. This vuln is only true for versions prior to 4.8.0 as described here: https://nvd.nist.gov/vuln/detail/CVE-2022-0839 and here: https://github.com/liquibase/liquibase/commit/33d9d925082097fb1a3d2fc8e44423d964cd9381

**How to reproduce it (as minimally and precisely as possible)**
Create a Dockerfile with the content below and scan it with anchore:

```
FROM liquibase/liquibase:4.9.1

USER root

RUN apt update \
    && apt full-upgrade -y \
    && apt-get remove -y unzip \
    && apt-get remove --purge -y libldap-2.4-2 \
    && apt-get remove --purge -y libldap-common \
    && apt-get install -y zlib1g \
    && apt-get install -y libsasl2-2 \
    && apt-get install -y openssl=1.1.1n-0+deb10u3 \
    && apt-get install -y libssl1.1=1.1.1n-0+deb10u3 \
    && apt-get install -y libgnutls30=3.6.7-4+deb10u9 \
    && apt-get autoclean \
    && apt-get autoremove -y

# CVE-2012-3324
RUN rm -f /liquibase/lib/jcc-11.5.6.0.jar
# CVE-2021-23463
RUN rm -f /liquibase/lib/h2-1.4.200.jar

USER liquibase
```

**Anything else we need to know**
Engine DB Version: 0.0.16
Engine Code Version: 1.1.0

**Comment by willmurphyscode** [comment]
Hi @nvp152, thanks for reporting this issue. I'm trying to reproduce it, but I haven't been able to. Here's what I've tried:

```
grype --platform linux/amd64 liquibase/liquibase:4.9.1 | grep CVE-2022-0839
```

But this prints `No vulnerabilities found`.

I've also tried building the Dockerfile you suggested in the original post, but have had to modify it a bit in order to get it to build:

```
FROM --platform=linux/amd64 liquibase/liquibase:4.9.1

USER root

ENV DEBIAN_FRONTEND=noninteractive

RUN apt update \
    && apt full-upgrade -y --allow-downgrades \
    && apt-get remove -y --allow-downgrades unzip \
    && apt-get remove --purge -y --allow-downgrades libldap-2.4-2 \
    && apt-get remove --purge -y --allow-downgrades libldap-common \
    && apt-get install -y --allow-downgrades zlib1g \
    && apt-get install -y --allow-downgrades libsasl2-2 \
    && apt-get install -y --allow-downgrades libgnutls30 \
    && apt-get install -y --allow-downgrades openssl=1.1.1n-0+deb10u3 \
    && apt-get install -y --allow-downgrades libssl1.1=1.1.1n-0+deb10u3 \
    && apt-get autoclean \
    && apt-get autoremove -y --allow-downgrades

# # CVE-2012-3324
# RUN rm -f /liquibase/lib/jcc-11.5.6.0.jar
# # CVE-2021-23463
# RUN rm -f /liquibase/lib/h2-1.4.200.jar

USER liquibase
```

The changes are:

1. Passing `--allow-downgrades`, since I think the base image includes some of these dependencies at a higher version now
2. Unpinning `libgnutls30` because the requested version isn't availabe
3. Setting `DEBIAN_FRONTEND=noninteractive` in the environment (otherwise the shell output from a build is completely swamped in warnings about a missing perl dependency)
4. Removing the two `rm` statements at the end of the file, since I thought maybe these removed vulnerable files.

Building and scanning an image with these changes, however, doesn't output `CVE-2022-0839`, and without these changes, I'm not able to get the image to build.

If you believe this is still an issue, and would like us to keep investigating, would you mind providing a new Dockerfile, or a link to a publicly hosted image or repo that exhibits this false positive? Thanks!

**Comment by willmurphyscode** [comment]
Hi @nvp152, thanks for reporting this issue! I haven't been able to reproduce it (see previous comment). If you still believe this is an issue, would you mind providing information on how to produce it today? Thanks!
