### ISSUE TITLE
Grype database has missing CVSS vectors

### ISSUE THREAD

**Issue by cpendery** [anchore/grype#904]
**What happened**:
`GHSA-hggm-jpg3-v476` has CVSS v3.1 vectors, but the list is reported empty in Grype's databases

**What you expected to happen**:
I'd expect the vectors that exist to be reported

**How to reproduce it (as minimally and precisely as possible)**:
View `GHSA-hggm-jpg3-v476` in the most recent Grype database and then view https://github.com/advisories/GHSA-hggm-jpg3-v476

db sha: `sha256:f0a066ce143857cbbb1cf87369c99712b750c703dae71f2a646267f2deec1584`
db built: `2022-08-29 08:17:05 +0000 UTC`

**Anything else we need to know?**:

**Environment**:
- Output of `grype version`: `0.48.0`
- OS (e.g: `cat /etc/os-release` or similar): MacOS

**Comment by kzantow** [comment]
Hi @cpendery -- I had a look in the database and see that there are no cvss entries for that particular vulnerability. It looks like the GHSA entries do not have the cvss vectors because the data comes from NVD, as I understand it. What are you expecting to happen here?

@wagoodman -- do you have any thoughts here?

**Comment by westonsteimel** [comment]
@kzantow GHSA's do have CVSS vectors in them sometimes, the feed drivers in enterprise just aren't currently including them.  It requires changes in the enterprise driver and then grype-db-builder
