### ISSUE TITLE
False Negative CVE-2007-4559

### ISSUE THREAD

**Issue by spiffcs** [anchore/grype#940]
**What happened**:
Scanning `python:slim` with grype does not surface [CVE-2007-4559](https://nvd.nist.gov/vuln/detail/CVE-2007-4559).

**What you expected to happen**:
CVE-2007-4559 should be surfaced for all python versions at the moment

**How to reproduce it (as minimally and precisely as possible)**:
`grype python:slim`

`CVE-2007-4559` does not appear in the results

**Anything else we need to know?**:
Small context [here](https://www.theregister.com/2022/09/22/python_vulnerability_tarfile/)

**Environment**:
- Output of `grype version`: `0.50.2`
- OS (e.g: `cat /etc/os-release` or similar): darwin/amd64

**Comment by captn3m0** [comment]
Unless Python is planning to fix this, reporting this en-masse will cause needless false positives.

**Comment by westonsteimel** [comment]
We are working on a labelling effort to help with understanding changes in grype matching quality and this serves as a good candidate for the case where we don't catch things because we don't know about the binaries at all since they aren't installed by a package manager.  We created this specifically so we don't forget to capture those cases

**Comment by captn3m0** [comment]
See https://github.com/anchore/syft/issues/1197 for detection problems on binaries installed outside of package manager (includes `python:slim`).

**Comment by tgerla** [comment]
The latest version of grype successfully identifies this CVE so I'll go ahead and close this issue.
