### ISSUE TITLE
grype cannot be used, because modify  syft CycloneDX format json result file.

### ISSUE THREAD

**Issue by chuangsheng** [anchore/grype#953]
**What happened**:
grype cannot be used, because modify  syft CycloneDX format json result file.
**What you expected to happen**:
I wonder what happened~
**How to reproduce it (as minimally and precisely as possible)**:
When I modify the "properties" content in the CycloneDX result file, "name": "syft: package: language", change "syft: package: language" to "demo: package: language" or "package: language" (delete the character 'syft:'), and then use grype for analysis, grype cannot be used. 
**Anything else we need to know?**:

**Environment**:
- Output of `grype version`: v0.50.2    Syft version 0.58.0
- OS (e.g: `cat /etc/os-release` or similar): windows 10 Pro

**Comment by kzantow** [comment]
Hi @chuangsheng -- First of all: _why_ are you changing this file? Secondly, is it even valid CycloneDX?

Grype does a best effort given a CycloneDX file, but there is some information in one of those files generated from Syft that other SBOM generators probably don't include. Generally speaking, if the PURLs are the same, the Grype analysis should be the same. But this is only for certain package ecosystems. If Grype has to do CPE matching, and you're removing the additional CPEs Grype needs, it definitely won't work. This is a known limitation due to CycloneDX only allowing a single CPE and won't likely be fixed until CycloneDX improves the format to allow multiple CPEs.

**Comment by chuangsheng** [comment]
> 

Thank you for your reply.
I may have misunderstood it. I think the string "name": "syft: package: language" in the syft result file is a meaningless character^_^
