### ISSUE TITLE
separate docker tests from the unit-tests

### ISSUE THREAD

**Issue by 06kellyjac** [anchore/grype#969]
**What would you like to be added**:

Currently there are several tests that depend on having `docker` in the path (and potentially the docker socket & internet running, not investigated much further)
e.g. "TestSarifPresenterImage", "Test_imageToSarifReport", "TestSarifPresenterImage" etc

I'd rather the unit-tests be standalone

**Why is this needed**:

Allow for running the unit-tests without `docker` either by default, or with some kind of opt-out tag or env var

**Additional context**:

Building grype in a hermetic sandbox

**Comment by kzantow** [comment]
This is a great idea. We do use Docker for a lot of things, since we're scanning images etc., so obviously cant get rid of it altogether, but making the _unit tests_ execute without docker seems like a good change. We have _integration tests_ as well, which would have to create images and such.

Do you happen to know offhand which tests might be candidates for moving?

PRs are definitely welcome!

**Comment by 06kellyjac** [comment]
Yup

https://github.com/nixos/nixpkgs/blob/master/pkgs/tools/security/grype/default.nix#L65-L88

Looking at the errors someone familiar with the code could probably tell which parts of the codebase are relevant

**Comment by kzantow** [comment]
Thanks for the follow-up @06kellyjac! We will definitely see what we can do here
