### ISSUE TITLE
( grype -o table ) : Unable to capture  output into specified logfile _OR_ any output file

### ISSUE THREAD

**Issue by freedom-isnotanarchy** [anchore/grype#998]
**What happened**:

SUMMARY:
( grype -o table ) : Unable to capture this output into specified logfile _OR_ any output file

When using `grype -o table` from a bash session on a Mac ?
I could not capture this output, to a file.

`export GRYPE_OUTPUT=table ; export GRYPE_LOG_FILE=junk_log_file.table`

**What you expected to happen**:

```
$   export GRYPE_OUTPUT=table
$   export GRYPE_LOG_FILE=junk_log_file.table
$   rm junk_log_file.table
$    grype    .
rm: junk_log_file.table: No such file or directory

 ✔ Vulnerability DB        [no update available]
 ✔ Indexed .
 ⠧ Cataloging packages     [packages 0]

spring-core                     5.2.9.RELEASE             java-archive  CVE-2016-1000027     Critical
woodstox-core                   5.3.0           5.4.0     java-archive  GHSA-fv22-xp26-mm9w  High
xmlsec                          2.1.4           2.1.7     java-archive  GHSA-j8wc-gxx9-82hx  High
```

**How to reproduce it (as minimally and precisely as possible)**:

The logfile, specified in the Env Variable is in fact, created.

However, this new logfile, is zero bytes:
```
-rw-r--r--@  1 605  staff     0B Nov 16 17:02 junk_log_file.table  <===
drwxr-xr-x  10 605  staff   320B Nov 16 17:02 .
```

**Anything else we need to know?**:

**Environment**:
- Output of `grype version`:
```
 grype version
Application:          grype
Version:              0.52.0
Syft Version:         v0.60.3
BuildDate:            2022-11-03T17:15:32Z
GitCommit:            c8ddd7e218f63eb3adac1ec98ba9d8db9f3f3fec
GitDescription:       v0.52.0
Platform:             darwin/amd64
GoVersion:            go1.18.7
Compiler:             gc
Supported DB Schema:  5
```

- OS (e.g: `cat /etc/os-release` or similar):
`MacOS Ventura 13.01`

**LINKS**:
https://github.com/anchore/grype/issues/648
https://github.com/anchore/grype/issues/808

**Comment by kzantow** [comment]
Hi @freedom-isnotanarchy -- I think the issue is you don't actually have any log messages -- the TUI output like `✔ Vulnerability DB        [no update available]` is not considered logging and wouldn't be written to the log, and the _report_ output is also not considered logging. You could run `grype -vv` to generate verbose logging and verify things _are_ actually written to the file.

However, logs and report output are two different things. If you're looking to capture the actual grype output, you should use either stdout redirection like `grype > some.file` or the `--file` flag: `grype --file some.file`.

**Comment by kieranswhite** [comment]
Did you have any joy with this @freedom-isnotanarchy? I am having a similar issue with the json output type having a 0 byte file. From what I can see the file is created when the grype scan starts so and just never updated afterwards.

**Comment by kieranswhite** [comment]
Hi @kzantow, Thanks for responding.

We are using the following command to scan our Docker images inside our GitLab CI runners.

```grype ${IMAGE_PATH} --scope squashed --only-fixed --fail-on Critical-o json --file $CI_PROJECT_DIR/report.json || (true && touch FAILED)```

The issue appears to be intermittent for us and sometimes we get an output, sometimes we don't (even when using the same image).


Below is an example of the log output we are seeing. The log lines are identical between runs that return a 0 byte JSON and a "full" JSON file.
![image](https://user-images.githubusercontent.com/6289007/229740718-298a92c4-2806-46a8-ae35-cb85b39f8aee.png)

We did notice that the method used to write files changed as of `v0.52.0` https://github.com/anchore/grype/commit/c8ddd7e218f63eb3adac1ec98ba9d8db9f3f3fec to use `os.WriteFile` rather than `ioutil.WriteFile`. Could this be related?

Many thanks,

Kieran

**Comment by kzantow** [comment]
@kieranswhite I'm curious -- if you use output redirection, e.g.:
```
grype ${IMAGE_PATH} --scope squashed --only-fixed --fail-on critical -o json > $CI_PROJECT_DIR/report.json
```
... does this ever result in a size 0 file? or is this only when using the `--file` option?

**Comment by tgerla** [comment]
Since we haven't heard back in a while we'll go ahead and close this issue, but feel free to reopen it or open a new one if you are still affected. Thanks!
