### ISSUE TITLE
Some rust-crate false positives

### ISSUE THREAD

**Issue by L1ghtman2k** [anchore/grype#999]
**What happened**:
Few false positives when scanning SBOMs of a Cargo.lock file
**What you expected to happen**:
No False positives

**How to reproduce it (as minimally and precisely as possible)**:
SBOM File:
[sbom.txt](https://github.com/anchore/grype/files/10037819/sbom.txt)
```
NAME        INSTALLED  FIXED-IN  TYPE        VULNERABILITY   SEVERITY
loom        0.5.6                rust-crate  CVE-2019-14432  High
openssl     0.10.42              rust-crate  CVE-2011-1945   Low
openssl     0.10.42              rust-crate  CVE-2011-4577   Medium
openssl     0.10.42              rust-crate  CVE-2011-4619   Medium
openssl     0.10.42              rust-crate  CVE-2013-6449   Medium
openssl     0.10.42              rust-crate  CVE-2014-0076   Low
openssl     0.10.42              rust-crate  CVE-2015-4000   Low
openssl     0.10.42              rust-crate  CVE-2016-2106   High
openssl     0.10.42              rust-crate  CVE-2016-2107   Medium
openssl     0.10.42              rust-crate  CVE-2010-5298   Medium
openssl     0.10.42              rust-crate  CVE-2012-0027   Medium
openssl     0.10.42              rust-crate  CVE-2016-2176   High
openssl     0.10.42              rust-crate  CVE-2010-4252   High
openssl     0.10.42              rust-crate  CVE-2011-4576   Medium
openssl     0.10.42              rust-crate  CVE-2016-2109   High
openssl     0.10.42              rust-crate  CVE-2021-4044   High
openssl     0.10.42              rust-crate  CVE-2011-4108   Medium
openssl     0.10.42              rust-crate  CVE-2016-2108   Critical
openssl     0.10.42              rust-crate  CVE-2016-7056   Medium
pear        0.2.3                rust-crate  CVE-2009-4024   High
pear        0.2.3                rust-crate  CVE-2009-4025   High
prometheus  0.13.3               rust-crate  CVE-2019-3826   Medium
```

As far as I know, none of these CVEs apply to the particular crates 

**Environment**:
```
Application:          grype
Version:              0.51.0
Syft Version:         v0.59.0
BuildDate:            2022-10-17T23:56:55Z
GitCommit:            4cda526992d5003dcbab68c9a7479a653dfde008
GitDescription:       v0.51.0
Platform:             linux/amd64
GoVersion:            go1.18.7
Compiler:             gc
Supported DB Schema:  5
```

**Comment by willmurphyscode** [comment]
Hi @L1ghtman2k, thanks for reporting this!

Digging into one of these that is from a more recent year:

CVE-2019-14432 from https://nvd.nist.gov/vuln/detail/CVE-2019-14432
matched artifact is:
   loom - pkg:cargo/loom@0.5.6
match type is cpe-match
CPEs 
  - `cpe:2.3:a:loom:loom:0.5.6:*:*:*:*:*:*:*`

URLs:
  - https://nvd.nist.gov/vuln/detail/CVE-2019-14432
  - https://thomask.sdf.org/blog/2019/08/07/cve-2019-14432-loom-desktop-rce-vulnerability.html
  - https://www.loom.com/blog/loom-desktop-application-security-fix/

It looks like the SBOM contains https://crates.io/crates/loom/0.5.6, but from that we generate the CPE `cpe:2.3:a:loom:loom:0.5.6:*:*:*:*:*:*:*`, which matches https://nvd.nist.gov/vuln/detail/CVE-2019-14432, which is a vulnerability against a desktop app for Mac with the same name. I'm applying a label indicating that this is a CPE-caused false positive, so that we can begin investigating that type of false positive as a groupe.

**Comment by willmurphyscode** [comment]
Hi @L1ghtman2k,

For Rust packages, we have switched from using CPEs to match (which can result in this type of cross-ecosystem confusion) to using PURLs to match against GHSA. You can read more about that here: https://anchore.com/blog/say-goodbye-to-false-positives/

I'm closing this since I believe this class of issue is fixed, but please let us know if we've missed something.
